# -*- coding: utf-8 -*-
"""Final_Descriptive_YWS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S1pteWcNoDC5TQQa75SfMVWbmuxdoOp1

# Data Inspection
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

df = pd.read_csv("/content/Descriptivecleaned_capstone_data.csv")

df.shape

df.info

missing_summary = pd.DataFrame({
    "Variable": df.columns,
    "Missing Count": df.isnull().sum().values,
    "Missing Percent": (df.isnull().mean().values * 100).round(2)
})

missing_summary = missing_summary.sort_values(
    by="Missing Percent",
    ascending=False
)

missing_summary[missing_summary["Missing Count"] > 0].head(15)

# Dataset Overview Table
dataset_overview = pd.DataFrame({
    "Metric": [
        "Number of respondents",
        "Number of variables",
        "Valid GAD-2 scores",
        "Valid PHQ-2 scores",
        "Valid PTSD scores",
        "Missing GAD-2 scores",
        "Missing PHQ-2 scores",
        "Missing PTSD scores"
    ],
    "Value": [
        df.shape[0],
        df.shape[1],
        df["gad_total"].notna().sum(),
        df["phq_total"].notna().sum(),
        df["ptsd_total"].notna().sum(),
        df["gad_total"].isna().sum(),
        df["phq_total"].isna().sum(),
        df["ptsd_total"].isna().sum()
    ]
})

dataset_overview

demographic_vars = [
    "age",
    "gender_group",
    "education_group",
    "employment_group",
    "marital_status",
    "resident_status",
    "region",
    "living_area"
]

socioeconomic_vars = [
    "income_group",
    "financial_struggle_group",
    "bill_difficulty_group",
    "income_stability_group",
    "financial_stress_group",
    "healthcare_access_group",
    "housing_group",
    "conflict_impact_group",
    "service_access_group"
]

mental_health_scores = [
    "gad_total",
    "phq_total",
    "ptsd_total"
]

mental_health_severity = [
    "anxiety_status",
    "depression_status",
    "ptsd_status"
]

mental_health_binary = [
    "anxiety_binary",
    "depression_binary",
    "ptsd_binary"
]

key_variables = {
    "Demographic Variables": demographic_vars,
    "Socioeconomic Variables": socioeconomic_vars,
    "Mental Health Scores": mental_health_scores,
    "Mental Health Severity": mental_health_severity,
    "Mental Health Binary": mental_health_binary
}

for category, variables in key_variables.items():
    print(f"{category}: {variables}")

variable_descriptions = {
    "age": "Respondent age in years (numeric)",
    "gender_group": "Gender identity (grouped)",
    "education_group": "Highest education level completed (grouped)",
    "employment_group": "Current employment status (grouped)",
    "marital_status": "Marital status",
    "resident_status": "Current residency situation (grouped)",
    "region": "State or region within Myanmar",
    "living_area": "Urban vs Rural classification",
    "income_group": "Monthly household income range (grouped)",
    "financial_struggle_group": "Frequency of struggling to cover expenses (grouped)",
    "bill_difficulty_group": "Difficulty paying bills (grouped)",
    "income_stability_group": "Perceived income stability (grouped)",
    "financial_stress_group": "Financial stress affecting sleep (grouped)",
    "healthcare_access_group": "Healthcare access status (grouped)",
    "housing_group": "Housing stability status (grouped)",
    "conflict_impact_group": "Conflict impact assessment (grouped)",
    "service_access_group": "Access to essential services (grouped)",
    "gad_total": "Generalized Anxiety Disorder (GAD-7) total score",
    "phq_total": "Patient Health Questionnaire (PHQ-9) total score",
    "ptsd_total": "Post-Traumatic Stress Disorder (PCL-5) total score",
    "anxiety_status": "Categorical severity of anxiety",
    "depression_status": "Categorical severity of depression",
    "ptsd_status": "Categorical severity of PTSD",
    "anxiety_binary": "Binary indicator for anxiety symptoms",
    "depression_binary": "Binary indicator for depressive symptoms",
    "ptsd_binary": "Binary indicator for PTSD symptoms"
}

print("## Key Variables")

for category_name, var_list in key_variables.items():
    display_category_name = ""
    if category_name == "Demographic Variables":
        display_category_name = "Demographics"
    elif category_name == "Socioeconomic Variables":
        display_category_name = "Socioeconomic Conditions"
    else:
        display_category_name = category_name.replace(' Variables', '')

    print(f"\n▸ {display_category_name}")
    print("  ·····························································")
    for var in var_list:
        description = variable_descriptions.get(var, "Description not available")
        print(f"    {var:<25} {description}")

demographic_vars = [
    "age",
    "gender_group",
    "education_group",
    "employment_group",
    "marital_status",
    "resident_status",
    "region",
    "living_area"
]

socioeconomic_vars = [
    "income_group",
    "financial_struggle_group",
    "bill_difficulty_group",
    "income_stability_group",
    "financial_stress_group",
    "healthcare_access_group",
    "housing_group",
    "conflict_impact_group",
    "service_access_group"
]

mental_health_scores = [
    "gad_total",
    "phq_total",
    "ptsd_total"
]

mental_health_severity = [
    "anxiety_status",
    "depression_status",
    "ptsd_status"
]

mental_health_binary = [
    "anxiety_binary",
    "depression_binary",
    "ptsd_binary"
]

required_vars = (
    demographic_vars
    + socioeconomic_vars
    + mental_health_scores
    + mental_health_severity
    + mental_health_binary
)

missing_vars = [col for col in required_vars if col not in df.columns]

missing_vars

"""# Demographic"""

def categorical_summary(df, column):
    summary = df[column].value_counts(dropna=False).reset_index()
    summary.columns = ["Category", "Count"]
    summary["Percent"] = (summary["Count"] / len(df) * 100).round(2)
    summary.insert(0, "Variable", column)
    return summary

demographic_categorical_vars = [
    "gender_group",
    "education_group",
    "employment_group",
    "marital_status",
    "resident_status",
    "region",
    "living_area"
]

demographic_summary = pd.concat(
    [categorical_summary(df, col) for col in demographic_categorical_vars],
    ignore_index=True
)

demographic_summary

age_summary = pd.DataFrame({
    "Variable": ["age"],
    "Count": [df["age"].count()],
    "Missing": [df["age"].isna().sum()],
    "Mean": [df["age"].mean()],
    "Median": [df["age"].median()],
    "Std": [df["age"].std()],
    "Min": [df["age"].min()],
    "Max": [df["age"].max()]
}).round(2)

age_summary

demographic_summary.head(20)

"""# Socioeconomic"""

socioeconomic_summary = pd.concat(
    [categorical_summary(df, col) for col in socioeconomic_vars],
    ignore_index=True
)

socioeconomic_summary

socioeconomic_summary = pd.concat(
    [categorical_summary(df, col) for col in socioeconomic_vars],
    ignore_index=True
)

socioeconomic_summary

for col in socioeconomic_vars:
    print("\n" + "="*60)
    print(col)
    print(df[col].value_counts(dropna=False))

"""# Mental Health"""

mental_health_score_summary = df[mental_health_scores].agg([
    "count", "mean", "median", "std", "min", "max"
]).T.round(2)

mental_health_score_summary

mental_health_score_summary_full = df[mental_health_scores].describe().T.round(2)

mental_health_score_summary_full

# Check Skewness
mental_health_skewness = df[mental_health_scores].skew().round(2).reset_index()
mental_health_skewness.columns = ["Mental Health Score", "Skewness"]

mental_health_skewness

"""### Mental Health Scores Distribution"""

os.makedirs("outputs/figures", exist_ok=True)

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

for i, col in enumerate(mental_health_scores):
    sns.histplot(df[col].dropna(), kde=True, ax=axes[i], bins=range(0, 13))
    axes[i].set_title(f'Distribution of {col.replace("_", " ").title()}')
    axes[i].set_xlabel(col.replace("_", " ").title())
    axes[i].set_ylabel('Frequency')

plt.tight_layout()
plt.savefig("outputs/figures/mental_health_scores_distribution.png")
plt.show()

fig, ax = plt.subplots(figsize=(8, 5))
sns.barplot(x='Mental Health Score', y='Skewness', data=mental_health_skewness, palette='viridis', hue='Mental Health Score', legend=False, ax=ax)
ax.set_title('Skewness of Mental Health Scores')
ax.set_xlabel('Mental Health Score')
ax.set_ylabel('Skewness Value')
plt.axhline(0, color='gray', linestyle='--', linewidth=0.8) # Add a line at 0 for reference
plt.tight_layout()
plt.savefig("outputs/figures/mental_health_scores_skewness.png")
plt.show()

"""## Mental Health Severity and Binary Prevalance"""

mental_health_severity_summary = pd.concat(
    [categorical_summary(df, col) for col in mental_health_severity],
    ignore_index=True
)

mental_health_severity_summary

mental_health_binary_summary = pd.concat(
    [categorical_summary(df, col) for col in mental_health_binary],
    ignore_index=True
)

mental_health_binary_summary

# Severity Summary
mental_health_severity_summary = pd.concat(
    [categorical_summary(df, col) for col in mental_health_severity],
    ignore_index=True
)

mental_health_severity_summary

"""# Descriptive comparsions by Socioeconomic variables"""

# Mean Mental Health Scores by SES Group
def group_score_summary(df, group_var, score_var):
    summary = df.groupby(group_var, dropna=False)[score_var].agg(
        Count="count",
        Mean="mean",
        Median="median",
        Std="std",
        Min="min",
        Max="max"
    ).round(2).reset_index()

    summary = summary.rename(columns={group_var: "Group"})
    summary.insert(0, "Group Variable", group_var)
    summary.insert(2, "Mental Health Score", score_var)

    return summary

group_score_summaries = []

for group_var in socioeconomic_vars:
    for score_var in mental_health_scores:
        temp = group_score_summary(df, group_var, score_var)
        group_score_summaries.append(temp)

group_score_summary_table = pd.concat(group_score_summaries, ignore_index=True)

group_score_summary_table

group_score_summary_table[
    group_score_summary_table["Group Variable"] == "income_group"
]

group_score_summary_table[
    group_score_summary_table["Group Variable"] == "housing_group"
]

group_score_summary_table[
    group_score_summary_table["Group Variable"] == "healthcare_access_group"
]

group_score_summary_table[
    group_score_summary_table["Group Variable"] == "financial_stress_group"
]

"""# Cross-tabulations Between SES Groups and Mental Health Binary Categories"""

def crosstab_count_percent(df, row_var, col_var):
    count_table = pd.crosstab(
        df[row_var],
        df[col_var],
        dropna=False
    )

    percent_table = pd.crosstab(
        df[row_var],
        df[col_var],
        normalize="index",
        dropna=False
    ) * 100

    percent_table = percent_table.round(2)

    count_long = count_table.reset_index().melt(
        id_vars=row_var,
        var_name="Mental Health Category",
        value_name="Count"
    )

    percent_long = percent_table.reset_index().melt(
        id_vars=row_var,
        var_name="Mental Health Category",
        value_name="Row Percent"
    )

    merged = count_long.merge(
        percent_long,
        on=[row_var, "Mental Health Category"]
    )

    merged = merged.rename(columns={row_var: "Group"})
    merged.insert(0, "Group Variable", row_var)
    merged.insert(2, "Mental Health Variable", col_var)

    return merged

#Crosstab Summary Table
crosstab_summaries = []

for group_var in socioeconomic_vars:
    for mh_var in mental_health_binary:
        temp = crosstab_count_percent(df, group_var, mh_var)
        crosstab_summaries.append(temp)

ses_mental_health_crosstab_summary = pd.concat(
    crosstab_summaries,
    ignore_index=True
)

ses_mental_health_crosstab_summary

ses_mental_health_crosstab_summary[
    ses_mental_health_crosstab_summary["Group Variable"] == "income_group"
]

ses_mental_health_crosstab_summary[
    ses_mental_health_crosstab_summary["Group Variable"] == "housing_group"
]

ses_mental_health_crosstab_summary[
    ses_mental_health_crosstab_summary["Group Variable"] == "healthcare_access_group"
]

ses_mental_health_crosstab_summary[
    ses_mental_health_crosstab_summary["Group Variable"] == "financial_stress_group"
]

"""# Correlation Descriptive"""

correlation_matrix = df[mental_health_scores].corr().round(2)

correlation_matrix

plt.figure(figsize=(6, 4))
sns.heatmap(
    correlation_matrix,
    annot=True,
    cmap="coolwarm",
    center=0,
    vmin=-1,
    vmax=1
)

plt.title("Correlation Matrix of Mental Health Scores")
plt.tight_layout()
plt.savefig("outputs/figures/mental_health_correlation_heatmap.png", dpi=300)
plt.show()

"""# Regression Lines for Mental Health Scores"""

fig, axes = plt.subplots(1, 3, figsize=(20, 6))

# GAD-total vs. PHQ-total
sns.regplot(data=df, x='gad_total', y='phq_total', ax=axes[0], scatter_kws={'alpha':0.6}, line_kws={'color':'red'})
axes[0].set_title('GAD-total vs. PHQ-total')
axes[0].set_xlabel('GAD-total Score')
axes[0].set_ylabel('PHQ-total Score')
axes[0].grid(True, linestyle='--', alpha=0.7)

# GAD-total vs. PTSD-total
sns.regplot(data=df, x='gad_total', y='ptsd_total', ax=axes[1], scatter_kws={'alpha':0.6}, line_kws={'color':'red'})
axes[1].set_title('GAD-total vs. PTSD-total')
axes[1].set_xlabel('GAD-total Score')
axes[1].set_ylabel('PTSD-total Score')
axes[1].grid(True, linestyle='--', alpha=0.7)

# PHQ-total vs. PTSD-total
sns.regplot(data=df, x='phq_total', y='ptsd_total', ax=axes[2], scatter_kws={'alpha':0.6}, line_kws={'color':'red'})
axes[2].set_title('PHQ-total vs. PTSD-total')
axes[2].set_xlabel('PHQ-total Score')
axes[2].set_ylabel('PTSD-total Score')
axes[2].grid(True, linestyle='--', alpha=0.7)

plt.tight_layout()
plt.savefig("outputs/figures/mental_health_score_regplots.png", dpi=300)
plt.show()

"""# Essential Plots for Descriptive Analysis"""

os.makedirs("outputs/figures", exist_ok=True)

for score in mental_health_scores:
    plt.figure(figsize=(8, 5))
    sns.histplot(df[score], bins=12, kde=True)
    plt.title(f"Distribution of {score.replace('_', ' ').title()}")
    plt.xlabel(score.replace("_", " ").title())
    plt.ylabel("Count")
    plt.tight_layout()
    plt.savefig(f"outputs/figures/{score}_distribution.png", dpi=300)
    plt.show()

os.makedirs("outputs/figures", exist_ok=True)

demographic_categorical_vars = [
    "gender_group",
    "education_group",
    "employment_group",
    "marital_status",
    "resident_status",
    "living_area"
]

# Plot categorical demographic variables
for col in demographic_categorical_vars:
    plt.figure(figsize=(10, 6))

    temp_df = df.copy()

    if col == 'marital_status':

        temp_df = temp_df[~temp_df[col].isin(['Divorced', 'Other'])]

    if col == 'resident_status':

        def recategorize_resident_status(status):
            if pd.isna(status):
                return np.nan
            elif status in ['Cox\'s Bazar Refugee Camp, Bangladesh', 'Refugee in Bangladesh', 'Refugee', 'Bangladesh']:
                return 'Migrated to abroad'
            elif status == 'Temporarily displaced within Myanmar':
                return 'Living in Myanmar'
            else:
                return status
        temp_df[col] = temp_df[col].apply(recategorize_resident_status)

        temp_df = temp_df[temp_df[col].isin(['Living in Myanmar', 'Migrated to abroad', 'Prefer not to say'])]


    plot_order = temp_df[col].value_counts(dropna=True).index
    sns.countplot(data=temp_df.dropna(subset=[col]), y=col, order=plot_order, palette='viridis', hue=col, legend=False)
    plt.title(f'Distribution of {col.replace("_", " ").title()}')
    plt.xlabel('Count')
    plt.ylabel(col.replace("_", " ").title())
    plt.tight_layout()
    plt.savefig(f"outputs/figures/{col}_distribution.png", dpi=300)
    plt.show()

# Demographic Profile Bar Charts
# -----------------------------

# Choose demographic variables for the figure as specified by the user
demo_vars = {
    "gender_group": "Gender",
    "education_group": "Education Level",
    "employment_group": "Employment Status",
    "marital_status": "Marital Status",
    "resident_status": "Residence Status",
    "living_area": "Living Area"
}

# Calculate the number of rows and columns for subplots dynamically
num_vars = len(demo_vars)
n_cols = 2
n_rows = (num_vars + n_cols - 1) // n_cols # Ceiling division

# Create subplots
fig, axes = plt.subplots(n_rows, n_cols, figsize=(14, n_rows * 5))
axes = axes.flatten() # Flatten for easy iteration

for i, (col, title) in enumerate(demo_vars.items()):
    ax = axes[i]
    temp_df = df.copy()

    # --- Specific filtering and recategorization ---
    if col == 'marital_status':
        # Filter to include only 'Single' and 'Married'
        temp_df = temp_df[temp_df[col].isin(['Single', 'Married'])]

    if col == 'resident_status':
        # Recategorize resident_status values
        def recategorize_status(status):
            if pd.isna(status):
                return np.nan
            elif status in ['Cox\'s Bazar Refugee Camp, Bangladesh', 'Refugee in Bangladesh', 'Refugee', 'Bangladesh']:
                return 'Migrated to abroad'
            elif status == 'Temporarily displaced within Myanmar':
                return 'Living in Myanmar'
            else:
                return status
        temp_df[col] = temp_df[col].apply(recategorize_status)

        temp_df = temp_df[temp_df[col].isin(['Living in Myanmar', 'Migrated to abroad', 'Prefer not to say'])]

    if not temp_df[col].dropna().empty:
        # Calculate percentage, dropping NaN values
        counts = temp_df[col].value_counts(dropna=True)
        percentages = (counts / len(temp_df) * 100).round(2)

        plot_df = percentages.reset_index()
        plot_df.columns = [col, "Percentage"]

        # Plot
        sns.barplot(
            data=plot_df,
            x="Percentage",
            y=col,
            ax=ax,
            palette='viridis',
            hue=col, # To prevent FutureWarning
            legend=False
        )

        # Add percentage labels
        for j, value in enumerate(plot_df["Percentage"]):
            ax.text(
                value + 0.5,
                j,
                f"{value:.2f}%",
                va="center",
                fontsize=10
            )

        ax.set_title(title, fontsize=13, fontweight="bold")
        ax.set_xlabel("Percentage (%)")
        ax.set_ylabel("")
        ax.set_xlim(0, max(plot_df["Percentage"]) + 10)
    else:

        ax.set_title(f'{title} (No data to display after filtering)', fontsize=13, fontweight='bold')
        ax.set_xticks([])
        ax.set_yticks([])
        ax.text(0.5, 0.5, 'No data', horizontalalignment='center', verticalalignment='center', transform=ax.transAxes)


for j in range(i + 1, len(axes)):
    fig.delaxes(axes[j])

plt.suptitle(
    "Demographic Profile of Respondents",
    fontsize=16,
    fontweight="bold"
)

plt.tight_layout(rect=[0, 0, 1, 0.96])
plt.show()

# Figure 4.2: Socioeconomic Hardship Profile
# ----------------------------------------------------

# Define socioeconomic hardship indicators
# Adjust category names only if your dataframe uses slightly different wording

hardship_indicators = {
    "financial_stress_group": {
        "label": "High financial stress",
        "hardship_categories": ["High financial stress", "High"]
    },
    "income_stability_group": {
        "label": "Unstable income",
        "hardship_categories": ["Unstable income", "Unstable"]
    },
    "bill_difficulty_group": {
        "label": "Difficulty paying bills",
        "hardship_categories": ["Difficulty paying bills", "Difficult", "Yes"]
    },
    "healthcare_access_group": {
        "label": "Limited/difficult healthcare access",
        "hardship_categories": ["Limited access", "Difficult access", "Limited / difficult access", "Difficult"]
    },
    "housing_group": {
        "label": "Unstable housing",
        "hardship_categories": ["Unstable housing", "Unstable"]
    },
    "conflict_impact_group": {
        "label": "Affected by conflict",
        "hardship_categories": ["Affected by conflict", "Affected", "Yes"]
    },
    "service_access_group": {
        "label": "Difficulty accessing services",
        "hardship_categories": ["Difficulty accessing services", "Difficult", "Yes"]
    },
    "financial_struggle_group": {
        "label": "Financial struggle",
        "hardship_categories": ["Financial struggle", "Struggling", "Yes", "High"]
    },
    "income_group": {
        "label": "Low income",
        "hardship_categories": ["Low income", "Low"]
    }
}

# Calculate hardship percentages
results = []

for col, info in hardship_indicators.items():
    if col in df.columns:
        total = df[col].notna().sum()

        hardship_count = df[col].isin(info["hardship_categories"]).sum()
        hardship_percent = (hardship_count / total * 100) if total > 0 else 0

        results.append({
            "Socioeconomic Indicator": info["label"],
            "Percentage": round(hardship_percent, 2)
        })
    else:
        print(f"Column not found: {col}")

hardship_df = pd.DataFrame(results)

# Sort from highest to lowest
hardship_df = hardship_df.sort_values(by="Percentage", ascending=True)

# Plot
plt.figure(figsize=(11, 7))

ax = sns.barplot(
    data=hardship_df,
    x="Percentage",
    y="Socioeconomic Indicator"
)

# Add percentage labels
for i, value in enumerate(hardship_df["Percentage"]):
    ax.text(
        value + 0.8,
        i,
        f"{value:.2f}%",
        va="center",
        fontsize=10
    )

plt.title(
    "Figure 4.2: Socioeconomic Hardship Profile of Respondents",
    fontsize=15,
    fontweight="bold"
)

plt.xlabel("Percentage of Respondents (%)")
plt.ylabel("")
plt.xlim(0, hardship_df["Percentage"].max() + 10)

plt.tight_layout()

# Save figure
plt.savefig("Figure_4_2_Socioeconomic_Hardship_Profile.png", dpi=300, bbox_inches="tight")

plt.show()

# Display table for checking
hardship_df.sort_values(by="Percentage", ascending=False)

key_group_vars = [        # boxplots by key SES groups:
    "income_group",
    "housing_group",
    "healthcare_access_group",
    "financial_stress_group"
]

for group_var in key_group_vars:
    for score in mental_health_scores:
        plt.figure(figsize=(9, 5))
        sns.boxplot(data=df, x=group_var, y=score)
        plt.title(f"{score.replace('_', ' ').title()} by {group_var.replace('_', ' ').title()}")
        plt.xlabel(group_var.replace("_", " ").title())
        plt.ylabel(score.replace("_", " ").title())
        plt.xticks(rotation=30)
        plt.tight_layout()
        plt.savefig(f"outputs/figures/{score}_by_{group_var}.png", dpi=300)
        plt.show()

for binary_var in mental_health_binary:
    plt.figure(figsize=(7, 5))
    sns.countplot(
        data=df,
        x=binary_var,
        order=df[binary_var].value_counts(dropna=False).index
    )
    plt.title(f"Prevalence of {binary_var.replace('_', ' ').title()}")
    plt.xlabel(binary_var.replace("_", " ").title())
    plt.ylabel("Count")
    plt.xticks(rotation=20)
    plt.tight_layout()
    plt.savefig(f"outputs/figures/{binary_var}_prevalence.png", dpi=300)
    plt.show()

mental_health_scores = ["gad_total", "phq_total", "ptsd_total"]

outlier_summary = []

for col in mental_health_scores:
    q1 = df[col].quantile(0.25)
    q3 = df[col].quantile(0.75)
    iqr = q3 - q1

    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr

    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]

    outlier_summary.append({
        "Variable": col,
        "Q1": q1,
        "Q3": q3,
        "IQR": iqr,
        "Lower Bound": lower_bound,
        "Upper Bound": upper_bound,
        "Outlier Count": outliers.shape[0],
        "Outlier Percent": round(outliers.shape[0] / df[col].notna().sum() * 100, 2)
    })

outlier_summary = pd.DataFrame(outlier_summary)
outlier_summary

os.makedirs("outputs/figures", exist_ok=True)

for col in mental_health_scores:
    plt.figure(figsize=(10, 6))
    sns.scatterplot(x=df.index, y=df[col], alpha=0.6)

    # Get bounds from the previously calculated outlier_summary
    bounds_info = outlier_summary[outlier_summary['Variable'] == col]
    if not bounds_info.empty:
        lower_bound = bounds_info['Lower Bound'].iloc[0]
        upper_bound = bounds_info['Upper Bound'].iloc[0]

        plt.axhline(y=lower_bound, color='r', linestyle='--', label=f'Lower Bound ({lower_bound:.2f})')
        plt.axhline(y=upper_bound, color='r', linestyle='--', label=f'Upper Bound ({upper_bound:.2f})')

    plt.title(f'Scatter Plot of {col.replace("_", " ").title()} with Outlier Bounds')
    plt.xlabel('Respondent Index')
    plt.ylabel(col.replace("_", " ").title())
    plt.legend()
    plt.grid(True, linestyle='--', alpha=0.7)
    plt.tight_layout()
    plt.savefig(f"outputs/figures/{col}_outlier_scatterplot.png", dpi=300)
    plt.show()

os.makedirs("outputs/figures", exist_ok=True)

for group_var in socioeconomic_vars:
    for mh_var in mental_health_binary:
        plot_data = ses_mental_health_crosstab_clean[
            (ses_mental_health_crosstab_clean['Group Variable'] == group_var) &
            (ses_mental_health_crosstab_clean['Mental Health Variable'] == mh_var)
        ]

        # Pivot the data for stacked bar chart
        pivot_table = plot_data.pivot_table(
            index='Group',
            columns='Mental Health Category',
            values='Row Percent'
        )

        # Fill NaN with 0 for categories not present in a group (e.g., if a group has 0% of a certain mental health category)
        pivot_table = pivot_table.fillna(0)

        # Sort columns to ensure consistent stacking order (e.g., 'No/low' first, then 'symptoms')
        # This assumes consistent naming conventions
        sorted_columns = [col for col in pivot_table.columns if 'No/low' in col] + \
                         [col for col in pivot_table.columns if 'symptoms' in col]
        pivot_table = pivot_table[sorted_columns]

        if not pivot_table.empty:
            fig, ax = plt.subplots(figsize=(10, 6))
            pivot_table.plot(kind='bar', stacked=True, ax=ax, cmap='viridis')

            ax.set_title(f'Prevalence of {mh_var.replace("_", " ").title()} by {group_var.replace("_", " ").title()}')
            ax.set_xlabel(group_var.replace("_", " ").title())
            ax.set_ylabel('Percentage (%)')
            ax.tick_params(axis='x', rotation=45)
            ax.legend(title='Mental Health Category', bbox_to_anchor=(1.05, 1), loc='upper left')
            ax.grid(axis='y', linestyle='--', alpha=0.7)
            plt.tight_layout()
            plt.savefig(f"outputs/figures/{mh_var}_by_{group_var}_stacked_bar.png", dpi=300)
            plt.show()

os.makedirs("outputs/figures", exist_ok=True)

socioeconomic_vars = [
    "income_group",
    "financial_struggle_group",
    "bill_difficulty_group",
    "income_stability_group",
    "financial_stress_group",
    "healthcare_access_group",
    "housing_group",
    "conflict_impact_group",
    "service_access_group"
]

for col in socioeconomic_vars:
    plt.figure(figsize=(10, 6))
    # Calculate percentages for plotting
    data = df[col].value_counts(normalize=True).mul(100).round(2).sort_values(ascending=True)

    # Explicitly set hue and legend=False to address FutureWarning
    sns.barplot(x=data.values, y=data.index, palette='viridis', hue=data.index, legend=False)
    plt.title(f'Distribution of {col.replace("_", " ").title()}')
    plt.xlabel('Percentage (%)')
    plt.ylabel(col.replace("_", " ").title())
    plt.grid(axis='x', linestyle='--', alpha=0.7)
    plt.tight_layout()
    plt.savefig(f"outputs/figures/{col}_horizontal_bar.png", dpi=300)
    plt.show()

# Socioeconomic vulnerability indicators

socioeconomic_profile = pd.DataFrame({
    "Indicator": [
        "Moderate/severe conflict impact",
        "Unstable income",
        "High financial stress",
        "Low income",
        "Unstable housing",
        "Limited/no healthcare access"
    ],
    "Percent": [
        68.11,
        64.12,
        45.51,
        39.53,
        36.54,
        23.92
    ]
})

# Sort for cleaner horizontal bar chart
socioeconomic_profile = socioeconomic_profile.sort_values("Percent", ascending=True)

plt.figure(figsize=(10, 6))
plt.barh(socioeconomic_profile["Indicator"], socioeconomic_profile["Percent"])

plt.title("Socioeconomic Vulnerability Among Respondents", fontsize=14, fontweight="bold")
plt.xlabel("Percentage of Respondents (%)")
plt.ylabel("")

# Add percentage labels
for index, value in enumerate(socioeconomic_profile["Percent"]):
    plt.text(value + 1, index, f"{value:.2f}%", va="center")

plt.xlim(0, 80)
plt.tight_layout()
plt.savefig("outputs/figures/socioeconomic_vulnerability_bar_chart.png", dpi=300, bbox_inches="tight")
plt.show()

# Mental health symptom prevalence

mental_health_prevalence = pd.DataFrame({
    "Indicator": [
        "Anxiety symptoms",
        "Depressive symptoms",
        "PTSD-related symptoms"
    ],
    "Percent": [
        65.45,
        63.79,
        68.11
    ]
})

plt.figure(figsize=(8, 6))
plt.bar(mental_health_prevalence["Indicator"], mental_health_prevalence["Percent"])

plt.title("Mental Health Symptom Burden", fontsize=14, fontweight="bold")
plt.xlabel("")
plt.ylabel("Percentage of Respondents (%)")
plt.ylim(0, 80)

# Add percentage labels
for index, value in enumerate(mental_health_prevalence["Percent"]):
    plt.text(index, value + 1, f"{value:.2f}%", ha="center")

plt.xticks(rotation=15)
plt.tight_layout()
plt.savefig("outputs/figures/mental_health_symptom_burden_bar_chart.png", dpi=300, bbox_inches="tight")
plt.show()

plt.figure(figsize=(10, 6))
sns.histplot(df['age'].dropna(), kde=True, bins=range(min(df['age'].dropna().astype(int)), max(df['age'].dropna().astype(int)) + 2))
plt.title('Distribution of Age', fontsize=14, fontweight='bold')
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.tight_layout()
plt.savefig("outputs/figures/age_distribution_new.png", dpi=300)
plt.show()

# Symptom prevalence by financial stress group

financial_stress_symptoms = pd.DataFrame({
    "Financial Stress": ["Low stress", "Moderate stress", "High stress"],
    "Anxiety": [32.31, 58.95, 85.40],
    "Depression": [41.54, 64.21, 74.45],
    "PTSD": [35.38, 72.63, 80.29]
})

financial_stress_long = financial_stress_symptoms.melt(
    id_vars="Financial Stress",
    var_name="Mental Health Indicator",
    value_name="Percent"
)

plt.figure(figsize=(10, 6))
sns.barplot(
    data=financial_stress_long,
    x="Financial Stress",
    y="Percent",
    hue="Mental Health Indicator"
)

plt.title("Mental Health Symptoms by Financial Stress Level", fontsize=14, fontweight="bold")
plt.xlabel("Financial Stress Level")
plt.ylabel("Percentage of Respondents (%)")
plt.ylim(0, 95)
plt.legend(title="Indicator")

# Add labels
ax = plt.gca()
for container in ax.containers:
    ax.bar_label(container, fmt="%.1f%%", padding=3, fontsize=9)

plt.tight_layout()
plt.savefig("outputs/figures/financial_stress_mental_health_symptoms.png", dpi=300, bbox_inches="tight")
plt.show()

# Symptom prevalence by income group

income_symptoms = pd.DataFrame({
    "Income Group": ["High income", "Middle income", "Low income"],
    "Anxiety": [36.99, 71.03, 78.15],
    "Depression": [42.47, 66.36, 74.79],
    "PTSD": [46.58, 72.90, 77.31]
})

income_long = income_symptoms.melt(
    id_vars="Income Group",
    var_name="Mental Health Indicator",
    value_name="Percent"
)

plt.figure(figsize=(10, 6))
sns.barplot(
    data=income_long,
    x="Income Group",
    y="Percent",
    hue="Mental Health Indicator"
)

plt.title("Mental Health Symptoms by Income Group", fontsize=14, fontweight="bold")
plt.xlabel("Income Group")
plt.ylabel("Percentage of Respondents (%)")
plt.ylim(0, 90)
plt.legend(title="Indicator")

# Add labels
ax = plt.gca()
for container in ax.containers:
    ax.bar_label(container, fmt="%.1f%%", padding=3, fontsize=9)

plt.tight_layout()

plt.show()

housing_symptoms = pd.DataFrame({
    "Housing Group": ["Stable housing", "Unstable housing"],
    "Anxiety": [55.56, 82.73],
    "Depression": [56.08, 78.18],
    "PTSD": [61.90, 80.00]
})

housing_long = housing_symptoms.melt(
    id_vars="Housing Group",
    var_name="Mental Health Indicator",
    value_name="Percent"
)

plt.figure(figsize=(9, 6))
sns.barplot(
    data=housing_long,
    x="Housing Group",
    y="Percent",
    hue="Mental Health Indicator"
)

plt.title("Mental Health Symptoms by Housing Stability", fontsize=14, fontweight="bold")
plt.xlabel("Housing Group")
plt.ylabel("Percentage of Respondents (%)")
plt.ylim(0, 90)
plt.legend(title="Indicator")

# Add labels
ax = plt.gca()
for container in ax.containers:
    ax.bar_label(container, fmt="%.1f%%", padding=3, fontsize=9)

plt.tight_layout()
plt.savefig("outputs/figures/housing_group_mental_health_symptoms.png", dpi=300, bbox_inches="tight")
plt.show()

sns.set_theme(style="whitegrid", palette="deep")

financial_stress_symptoms = pd.DataFrame({
    "Financial Stress": ["Low stress", "Moderate stress", "High stress"],
    "Anxiety": [32.31, 58.95, 85.40],
    "Depression": [41.54, 64.21, 74.45],
    "PTSD": [35.38, 72.63, 80.29]
})

plt.figure(figsize=(12, 7))

plt.plot(
    financial_stress_symptoms["Financial Stress"],
    financial_stress_symptoms["Anxiety"],
    marker="o",
    label="Anxiety",
    linewidth=3,
    markersize=10
)

plt.plot(
    financial_stress_symptoms["Financial Stress"],
    financial_stress_symptoms["Depression"],
    marker="o",
    label="Depression",
    linewidth=3,
    markersize=10
)

plt.plot(
    financial_stress_symptoms["Financial Stress"],
    financial_stress_symptoms["PTSD"],
    marker="o",
    label="PTSD",
    linewidth=3,
    markersize=10
)

plt.title("Escalating Mental Health Symptoms with Increased Financial Stress", fontsize=18, fontweight="bold", pad=20) # More impactful title
plt.xlabel("Financial Stress Level", fontsize=14, labelpad=10)
plt.ylabel("Percentage of Respondents (%)", fontsize=14, labelpad=10)
plt.ylim(0, 100)
plt.legend(title="Mental Health Indicator", fontsize=12, title_fontsize=14, loc='upper left', bbox_to_anchor=(1,1)) # Larger legend text and moved to avoid overlap
plt.grid(axis="y", alpha=0.5, linestyle='--')

# Add labels on the lines
for col in ["Anxiety", "Depression", "PTSD"]:
    for i, value in enumerate(financial_stress_symptoms[col]):
        plt.text(i, value + 3, f"{value:.1f}%", ha="center", fontsize=11, fontweight='bold') # Larger, bold text labels

plt.xticks(fontsize=12)
plt.yticks(fontsize=12)

plt.tight_layout(rect=[0, 0, 0.85, 1]) # Adjust layout to make space for the legend
plt.savefig("outputs/figures/financial_stress_mental_health_line_chart_appealing.png", dpi=300, bbox_inches="tight") # Save with a new name
plt.show()

group_var = 'income_stability_group'
mh_vars = ['anxiety_binary', 'depression_binary', 'ptsd_binary']

for mh_var in mh_vars:
    plot_data = ses_mental_health_crosstab_clean[
        (ses_mental_health_crosstab_clean['Group Variable'] == group_var) &
        (ses_mental_health_crosstab_clean['Mental Health Variable'] == mh_var)
    ]

    # Pivot the data for stacked bar chart
    pivot_table = plot_data.pivot_table(
        index='Group',
        columns='Mental Health Category',
        values='Row Percent'
    )

    pivot_table = pivot_table.fillna(0)

    # Sort columns to ensure consistent stacking order
    sorted_columns = [col for col in pivot_table.columns if 'No/low' in col] + \
                     [col for col in pivot_table.columns if 'symptoms' in col]
    pivot_table = pivot_table[sorted_columns]

    if not pivot_table.empty:
        fig, ax = plt.subplots(figsize=(10, 6))
        pivot_table.plot(kind='bar', stacked=True, ax=ax, cmap='viridis')

        ax.set_title(f'Prevalence of {mh_var.replace("_", " ").title()} by {group_var.replace("_", " ").title()}')
        ax.set_xlabel(group_var.replace("_", " ").title())
        ax.set_ylabel('Percentage (%)')
        ax.tick_params(axis='x', rotation=45)
        ax.legend(title='Mental Health Category', bbox_to_anchor=(1.05, 1), loc='upper left')
        ax.grid(axis='y', linestyle='--', alpha=0.7)
        plt.tight_layout()
        plt.savefig(f"outputs/figures/{mh_var}_by_{group_var}_stacked_bar.png", dpi=300)
        plt.show()

roup_var = 'healthcare_access_group'
mh_vars = ['anxiety_binary', 'depression_binary', 'ptsd_binary']

for mh_var in mh_vars:
    plot_data = ses_mental_health_crosstab_clean[
        (ses_mental_health_crosstab_clean['Group Variable'] == group_var) &
        (ses_mental_health_crosstab_clean['Mental Health Variable'] == mh_var)
    ]

    # Pivot the data for stacked bar chart
    pivot_table = plot_data.pivot_table(
        index='Group',
        columns='Mental Health Category',
        values='Row Percent'
    )

    pivot_table = pivot_table.fillna(0)

    # Sort columns to ensure consistent stacking order
    sorted_columns = [col for col in pivot_table.columns if 'No/low' in col] + \
                     [col for col in pivot_table.columns if 'symptoms' in col]
    pivot_table = pivot_table[sorted_columns]

    if not pivot_table.empty:
        fig, ax = plt.subplots(figsize=(10, 6))
        pivot_table.plot(kind='bar', stacked=True, ax=ax, cmap='viridis')

        ax.set_title(f'Prevalence of {mh_var.replace("_", " ").title()} by {group_var.replace("_", " ").title()}')
        ax.set_xlabel(group_var.replace("_", " ").title())
        ax.set_ylabel('Percentage (%)')
        ax.tick_params(axis='x', rotation=45)
        ax.legend(title='Mental Health Category', bbox_to_anchor=(1.05, 1), loc='upper left')
        ax.grid(axis='y', linestyle='--', alpha=0.7)
        plt.tight_layout()
        plt.savefig(f"outputs/figures/{mh_var}_by_{group_var}_stacked_bar.png", dpi=300)
        plt.show()

group_var = 'housing_group'
mh_vars = ['anxiety_binary', 'depression_binary', 'ptsd_binary']

for mh_var in mh_vars:
    plot_data = ses_mental_health_crosstab_clean[
        (ses_mental_health_crosstab_clean['Group Variable'] == group_var) &
        (ses_mental_health_crosstab_clean['Mental Health Variable'] == mh_var)
    ]

    # Pivot the data for stacked bar chart
    pivot_table = plot_data.pivot_table(
        index='Group',
        columns='Mental Health Category',
        values='Row Percent'
    )

    pivot_table = pivot_table.fillna(0)

    # Sort columns to ensure consistent stacking order
    sorted_columns = [col for col in pivot_table.columns if 'No/low' in col] + \
                     [col for col in pivot_table.columns if 'symptoms' in col]
    pivot_table = pivot_table[sorted_columns]

    if not pivot_table.empty:
        fig, ax = plt.subplots(figsize=(10, 6))
        pivot_table.plot(kind='bar', stacked=True, ax=ax, cmap='viridis')

        ax.set_title(f'Prevalence of {mh_var.replace("_", " ").title()} by {group_var.replace("_", " ").title()}')
        ax.set_xlabel(group_var.replace("_", " ").title())
        ax.set_ylabel('Percentage (%)')
        ax.tick_params(axis='x', rotation=45)
        ax.legend(title='Mental Health Category', bbox_to_anchor=(1.05, 1), loc='upper left')
        ax.grid(axis='y', linestyle='--', alpha=0.7)
        plt.tight_layout()
        plt.savefig(f"outputs/figures/{mh_var}_by_{group_var}_stacked_bar.png", dpi=300)
        plt.show()

group_var = 'conflict_impact_group'
mh_vars = ['anxiety_binary', 'depression_binary', 'ptsd_binary']

for mh_var in mh_vars:
    plot_data = ses_mental_health_crosstab_clean[
        (ses_mental_health_crosstab_clean['Group Variable'] == group_var) &
        (ses_mental_health_crosstab_clean['Mental Health Variable'] == mh_var)
    ]

    # Pivot the data for stacked bar chart
    pivot_table = plot_data.pivot_table(
        index='Group',
        columns='Mental Health Category',
        values='Row Percent'
    )

    pivot_table = pivot_table.fillna(0)

    # Sort columns to ensure consistent stacking order
    sorted_columns = [col for col in pivot_table.columns if 'No/low' in col] + \
                     [col for col in pivot_table.columns if 'symptoms' in col]
    pivot_table = pivot_table[sorted_columns]

    if not pivot_table.empty:
        fig, ax = plt.subplots(figsize=(10, 6))
        pivot_table.plot(kind='bar', stacked=True, ax=ax, cmap='viridis')

        ax.set_title(f'Prevalence of {mh_var.replace("_", " ").title()} by {group_var.replace("_", " ").title()}')
        ax.set_xlabel(group_var.replace("_", " ").title())
        ax.set_ylabel('Percentage (%)')
        ax.tick_params(axis='x', rotation=45)
        ax.legend(title='Mental Health Category', bbox_to_anchor=(1.05, 1), loc='upper left')
        ax.grid(axis='y', linestyle='--', alpha=0.7)
        plt.tight_layout()
        plt.savefig(f"outputs/figures/{mh_var}_by_{group_var}_stacked_bar.png", dpi=300)
        plt.show()

group_var = 'service_access_group'
mh_vars = ['anxiety_binary', 'depression_binary', 'ptsd_binary']

for mh_var in mh_vars:
    plot_data = ses_mental_health_crosstab_clean[
        (ses_mental_health_crosstab_clean['Group Variable'] == group_var) &
        (ses_mental_health_crosstab_clean['Mental Health Variable'] == mh_var)
    ]

    # Pivot the data for stacked bar chart
    pivot_table = plot_data.pivot_table(
        index='Group',
        columns='Mental Health Category',
        values='Row Percent'
    )

    pivot_table = pivot_table.fillna(0)

    # Sort columns to ensure consistent stacking order
    sorted_columns = [col for col in pivot_table.columns if 'No/low' in col] + \
                     [col for col in pivot_table.columns if 'symptoms' in col]
    pivot_table = pivot_table[sorted_columns]

    if not pivot_table.empty:
        fig, ax = plt.subplots(figsize=(10, 6))
        pivot_table.plot(kind='bar', stacked=True, ax=ax, cmap='viridis')

        ax.set_title(f'Prevalence of {mh_var.replace("_", " ").title()} by {group_var.replace("_", " ").title()}')
        ax.set_xlabel(group_var.replace("_", " ").title())
        ax.set_ylabel('Percentage (%)')
        ax.tick_params(axis='x', rotation=45)
        ax.legend(title='Mental Health Category', bbox_to_anchor=(1.05, 1), loc='upper left')
        ax.grid(axis='y', linestyle='--', alpha=0.7)
        plt.tight_layout()
        plt.savefig(f"outputs/figures/{mh_var}_by_{group_var}_stacked_bar.png", dpi=300)
        plt.show()

group_var = 'financial_struggle_group'
mh_vars = ['anxiety_binary', 'depression_binary', 'ptsd_binary']

for mh_var in mh_vars:
    plot_data = ses_mental_health_crosstab_clean[
        (ses_mental_health_crosstab_clean['Group Variable'] == group_var) &
        (ses_mental_health_crosstab_clean['Mental Health Variable'] == mh_var)
    ]

    # Pivot the data for stacked bar chart
    pivot_table = plot_data.pivot_table(
        index='Group',
        columns='Mental Health Category',
        values='Row Percent'
    )

    pivot_table = pivot_table.fillna(0)

    # Sort columns to ensure consistent stacking order
    sorted_columns = [col for col in pivot_table.columns if 'No/low' in col] + \
                     [col for col in pivot_table.columns if 'symptoms' in col]
    pivot_table = pivot_table[sorted_columns]

    if not pivot_table.empty:
        fig, ax = plt.subplots(figsize=(10, 6))
        pivot_table.plot(kind='bar', stacked=True, ax=ax, cmap='viridis')

        ax.set_title(f'Prevalence of {mh_var.replace("_", " ").title()} by {group_var.replace("_", " ").title()}')
        ax.set_xlabel(group_var.replace("_", " ").title())
        ax.set_ylabel('Percentage (%)')
        ax.tick_params(axis='x', rotation=45)
        ax.legend(title='Mental Health Category', bbox_to_anchor=(1.05, 1), loc='upper left')
        ax.grid(axis='y', linestyle='--', alpha=0.7)
        plt.tight_layout()
        plt.savefig(f"outputs/figures/{mh_var}_by_{group_var}_stacked_bar.png", dpi=300)
        plt.show()

# Ensure outputs/figures directory exists
os.makedirs("outputs/figures", exist_ok=True)

# Assuming df, socioeconomic_vars, mental_health_binary, and ses_mental_health_crosstab_clean are already defined and available

for group_var in socioeconomic_vars:
    fig, axes = plt.subplots(1, 3, figsize=(20, 6), sharey=True)
    fig.suptitle(f'Prevalence of Mental Health Symptoms by {group_var.replace("_", " ").title()}', fontsize=16, fontweight='bold', y=1.05)

    # Collect handles and labels for a single figure legend from the first successful plot
    all_handles_for_figure = []
    all_labels_for_figure = []

    for i, mh_var in enumerate(mental_health_binary):
        ax = axes[i]
        plot_data = ses_mental_health_crosstab_clean[
            (ses_mental_health_crosstab_clean['Group Variable'] == group_var) &
            (ses_mental_health_crosstab_clean['Mental Health Variable'] == mh_var)
        ].copy() # Use .copy() to avoid SettingWithCopyWarning

        if not plot_data.empty:
            pivot_table = plot_data.pivot_table(
                index='Group',
                columns='Mental Health Category',
                values='Row Percent'
            )
            pivot_table = pivot_table.fillna(0)


            current_mh_categories = pivot_table.columns.tolist()


            no_low_categories = sorted([cat for cat in current_mh_categories if 'No/low' in cat])


            symptoms_categories = sorted([cat for cat in current_mh_categories if 'symptoms' in cat and 'No/low' not in cat])


            other_categories = sorted([cat for cat in current_mh_categories if cat not in no_low_categories + symptoms_categories])

            sorted_columns_for_stack = no_low_categories + symptoms_categories + other_categories


            sorted_columns_for_stack = [col for col in sorted_columns_for_stack if col in pivot_table.columns]

            if sorted_columns_for_stack:
                pivot_table = pivot_table[sorted_columns_for_stack]

            ax_plot = pivot_table.plot(kind='bar', stacked=True, ax=ax, cmap='viridis')

            ax.set_title(f'{mh_var.replace("_", " ").title()}', fontsize=12)
            ax.set_xlabel('')
            if i == 0:
                ax.set_ylabel('Percentage (%)')
            ax.tick_params(axis='x', rotation=45)
            ax.grid(axis='y', linestyle='--', alpha=0.7)


            handles, labels = ax_plot.get_legend_handles_labels()

            for h, l in zip(handles, labels):
                if l not in all_labels_for_figure:
                    all_handles_for_figure.append(h)
                    all_labels_for_figure.append(l)

            ax.get_legend().remove()

        else:
            ax.set_title(f'{mh_var.replace("_", " ").title()} (No Data)', fontsize=12)
            ax.text(0.5, 0.5, 'No data to display', horizontalalignment='center', verticalalignment='center', transform=ax.transAxes, fontsize=10)
            ax.set_xticks([])
            ax.set_yticks([])


    if all_handles_for_figure:

        unique_legend_data = dict(zip(all_labels_for_figure, all_handles_for_figure))
        sorted_labels = []
        if 'No/low anxiety symptoms' in unique_legend_data: sorted_labels.append('No/low anxiety symptoms')
        if 'Anxiety symptoms' in unique_legend_data: sorted_labels.append('Anxiety symptoms')
        if 'No/low depressive symptoms' in unique_legend_data: sorted_labels.append('No/low depressive symptoms')
        if 'Depressive symptoms' in unique_legend_data: sorted_labels.append('Depressive symptoms')
        if 'No/low PTSD symptoms' in unique_legend_data: sorted_labels.append('No/low PTSD symptoms')
        if 'PTSD symptoms' in unique_legend_data: sorted_labels.append('PTSD symptoms')


        for lbl in sorted(unique_legend_data.keys()):
            if lbl not in sorted_labels:
                sorted_labels.append(lbl)

        sorted_handles = [unique_legend_data[label] for label in sorted_labels if label in unique_legend_data]

        fig.legend(sorted_handles, sorted_labels, title='Mental Health Category', loc='center right', bbox_to_anchor=(1.08, 0.5), fontsize=10)

    plt.tight_layout(rect=[0, 0, 0.98, 0.98])
    plt.savefig(f"outputs/figures/mental_health_binary_by_{group_var}_combined_stacked_bar.png", dpi=300, bbox_inches='tight')
    plt.show()

print("Combined stacked bar charts for mental health symptoms by each socioeconomic variable have been generated and saved to 'outputs/figures/'.")

# Combined Figure: Mental Health Symptoms by SES Factors


# Mental health binary columns
mental_health_cols = {
    "anxiety_binary": "Anxiety",
    "depression_binary": "Depression",
    "ptsd_binary": "PTSD"
}

# Socioeconomic grouping variables
ses_vars = {
    "income_stability_group": "Income Stability",
    "healthcare_access_group": "Healthcare Access",
    "housing_group": "Housing Stability",
    "conflict_impact_group": "Conflict Impact",
    "service_access_group": "Service Access",
    "financial_struggle_group": "Financial Struggle"
}

# Function to detect symptom-present values
def is_symptom_present(series):
    # Convert to string to ensure .str accessor works
    return series.astype(str).str.contains('symptoms', case=False, na=False) & \
           ~series.astype(str).str.contains('No/low', case=False, na=False)

# Create one combined figure
fig, axes = plt.subplots(3, 2, figsize=(18, 18))
axes = axes.flatten()

combined_results = {}

for ax, (group_col, group_label) in zip(axes, ses_vars.items()):

    plot_data = []

    for mh_col, mh_label in mental_health_cols.items():

        if group_col in df.columns and mh_col in df.columns:

            temp = df[[group_col, mh_col]].dropna()

            grouped = temp.groupby(group_col)[mh_col].apply(
                lambda x: is_symptom_present(x).sum() / len(x) * 100
            ).reset_index()

            grouped.columns = [group_label, "Percentage"]
            grouped["Mental Health Outcome"] = mh_label

            plot_data.append(grouped)

        else:
            print(f"Missing column: {group_col} or {mh_col}")

    plot_df = pd.concat(plot_data, ignore_index=True)
    combined_results[group_label] = plot_df

    sns.barplot(
        data=plot_df,
        x=group_label,
        y="Percentage",
        hue="Mental Health Outcome",
        ax=ax
    )

    ax.set_title(
        f"Mental Health Symptoms by {group_label}",
        fontsize=13,
        fontweight="bold"
    )

    ax.set_xlabel("")
    ax.set_ylabel("Respondents with symptoms (%)")
    ax.set_ylim(0, min(100, plot_df["Percentage"].max() + 15))
    ax.tick_params(axis="x", rotation=25)

    # Add percentage labels
    for container in ax.containers:
        ax.bar_label(
            container,
            fmt="%.1f%%",
            fontsize=8,
            padding=2
        )

    ax.legend(title="", fontsize=9)

plt.suptitle(
    " Mental Health Symptoms by Socioeconomic Factors",
    fontsize=18,
    fontweight="bold"
)

plt.tight_layout(rect=[0, 0, 1, 0.97])

plt.savefig(
    "Figure_4_X_Mental_Health_Symptoms_by_Socioeconomic_Factors.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

#socioeconomic hardship indicators


hardship_indicators = {
    "financial_stress_group": {
        "label": "High financial stress",
        "hardship_categories": ["High financial stress", "High"]
    },
    "income_stability_group": {
        "label": "Unstable income",
        "hardship_categories": ["Unstable income", "Unstable"]
    },
    "bill_difficulty_group": {
        "label": "Difficulty paying bills",
        "hardship_categories": ["High"] # Updated to match actual data categories
    },
    "healthcare_access_group": {
        "label": "Limited/difficult healthcare access",
        "hardship_categories": ["Limited/no access"] # Updated to match actual data categories
    },
    "housing_group": {
        "label": "Unstable housing",
        "hardship_categories": ["Unstable housing", "Unstable"]
    },
    "conflict_impact_group": {
        "label": "Affected by conflict",
        "hardship_categories": ["Moderate/Severe Impact"] # Updated to match actual data categories
    },
    "service_access_group": {
        "label": "Difficulty accessing services",
        "hardship_categories": ["Hard"] # Updated to match actual data categories
    },
    "financial_struggle_group": {
        "label": "Financial struggle",
        "hardship_categories": ["Financial struggle", "Struggling", "Yes", "High"]
    },
    "income_group": {
        "label": "Low income",
        "hardship_categories": ["Low income", "Low"]
    }
}

# Calculate hardship percentages
results = []

for col, info in hardship_indicators.items():
    if col in df.columns:
        total = df[col].notna().sum()

        hardship_count = df[col].isin(info["hardship_categories"]).sum()
        hardship_percent = (hardship_count / total * 100) if total > 0 else 0

        results.append({
            "Socioeconomic Indicator": info["label"],
            "Percentage": round(hardship_percent, 2)
        })
    else:
        print(f"Column not found: {col}")

hardship_df = pd.DataFrame(results)

# Sort from highest to lowest
hardship_df = hardship_df.sort_values(by="Percentage", ascending=True)

# Plot
plt.figure(figsize=(11, 7))

ax = sns.barplot(
    data=hardship_df,
    x="Percentage",
    y="Socioeconomic Indicator"
)

# Add percentage labels
for i, value in enumerate(hardship_df["Percentage"]):
    ax.text(
        value + 0.8,
        i,
        f"{value:.2f}%",
        va="center",
        fontsize=10
    )

plt.title(
    "Socioeconomic Hardship Profile of Respondents",
    fontsize=15,
    fontweight="bold"
)

plt.xlabel("Percentage of Respondents (%)")
plt.ylabel("")
plt.xlim(0, hardship_df["Percentage"].max() + 10)

plt.tight_layout()

# Save figure
plt.savefig("Socioeconomic_Hardship_Profile.png", dpi=300, bbox_inches="tight")

plt.show()

# Display table for checking
hardship_df.sort_values(by="Percentage", ascending=False)

# Mental Health Symptom Burden


mental_health_binary = {
    "anxiety_binary": "Anxiety symptoms",
    "depression_binary": "Depressive symptoms",
    "ptsd_binary": "PTSD symptoms" # Corrected label here
}

burden_results = []

for col, label in mental_health_binary.items():
    if col in df.columns:
        valid_total = df[col].notna().sum()
        symptom_count = (df[col] == label).sum()
        symptom_percent = (symptom_count / valid_total * 100) if valid_total > 0 else 0

        burden_results.append({
            "Mental Health Outcome": label,
            "Symptom Present Count": symptom_count,
            "Valid Total": valid_total,
            "Percentage": round(symptom_percent, 2)
        })
    else:
        print(f"Column not found: {col}")

burden_df = pd.DataFrame(burden_results)
burden_df = burden_df.sort_values(by="Percentage", ascending=False)

plt.figure(figsize=(9, 6))

ax = sns.barplot(
    data=burden_df,
    x="Mental Health Outcome",
    y="Percentage"
)

for i, value in enumerate(burden_df["Percentage"]):
    ax.text(
        i,
        value + 1,
        f"{value:.2f}%",
        ha="center",
        va="bottom",
        fontsize=11
    )

plt.title(
    " Mental Health Symptom Burden Among Respondents",
    fontsize=15,
    fontweight="bold"
)

plt.xlabel("")
plt.ylabel("Percentage of Respondents (%)")
plt.ylim(0, burden_df["Percentage"].max() + 10)

plt.tight_layout()
plt.savefig("Figure_4_3_Mental_Health_Symptom_Burden.png", dpi=300, bbox_inches="tight")
plt.show()

burden_df







