# -*- coding: utf-8 -*-
"""Inferential_Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L2Dt1sw3QIbIkXKZPOVFU2XWOm9T4fB_

# Phase 1: Import Libraries and File Reading
"""



import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
!pip install pingouin
import pingouin as pg



df = pd.read_csv("/content/Data300csv.csv")

# Find the index of the last desired column
last_col_name = '27. In the past month, have you  felt guilty or unable to stop blaming yourself or others for the event(s) or any problem that event(s) may have caused? \n၂၇။ လွန်ခဲ့သော တစ်လအတွင်း ဖြစ်ပျက်ခဲ့သော အဖြစ်အပျက်များ သို့မဟုတ် ထိုအဖြစ်အပျက်များကြောင့် ဖြစ်ပေါ်လာသော ပြဿနာများအတွက် သင့်ကိုယ်သင် သို့မဟုတ် အခြားသူများကို အပြစ်တင်နေခြင်း (သို့မဟုတ်) အပြစ်ရှိသလို ခံစားနေရခြင်းများ ရှိပါသလား။  '
last_col_index = df.columns.get_loc(last_col_name)

# Select columns from index 1 (to drop 'Timestamp') up to and including the last desired column
df = df.iloc[:, 1:last_col_index + 1]

"""# Phase 2: Data Preprocessing"""

# Data Inspection
df.head()

df.shape

# Define the new column names in a list
new_column_names = [
    'age',
    'gender',
    'education',
    'employment_status',
    'marital_status',
    'household_income',
    'resident_status',
    'region',
    'migrated_country',
    'living_area',
    'financial_struggle',
    'bill_difficulty',
    'income_stability',
    'financial_stress',
    'healthcare_access',
    'housing_situation',
    'conflict_impact',
    'service_access',
    'gad1',
    'gad2',
    'phq1',
    'phq2',
    'ptsd1',
    'ptsd2',
    'ptsd3',
    'ptsd4',
    'ptsd5'
]

# Directly assign new column names to the DataFrame
df.columns = new_column_names

# Display the new columns to confirm
print("DataFrame columns after renaming:")
display(df.columns)

df.columns

df.info()

df_cat = df.select_dtypes(include="object")      #
df_num = df.select_dtypes(include=["int64", "float64"])

print("Categorical columns:", df_cat.shape[1], "→", df_cat.columns.tolist())
print("Numerical columns  :", df_num.shape[1], "→", df_num.columns.tolist())

# check missing values
missing_table = pd.DataFrame({
    'Missing Count': df.isnull().sum(),
    'Missing Percent': (df.isnull().sum() / len(df)) * 100
})

missing_table.sort_values(by='Missing Percent', ascending=False)

# Check unique values for Categorical variables
categorical_columns = [
    'gender',
    'education',
    'employment_status',
    'marital_status',
    'household_income',
    'resident_status',
    'region',
    'living_area',
    'financial_struggle',
    'bill_difficulty',
    'income_stability',
    'financial_stress',
    'healthcare_access',
    'housing_situation',
    'conflict_impact',
    'service_access'
]

for col in categorical_columns:
    print("\n" + "="*50)
    print(col)
    print(df[col].value_counts(dropna=False))

df = df.drop(columns=['migrated_country'])
df.shape

categorical_cols = [
    "gender", "education", "employment_status", "marital_status",
    "household_income", "resident_status", "region", "living_area",
    "financial_struggle", "bill_difficulty", "income_stability",
    "financial_stress", "healthcare_access", "housing_situation",
    "conflict_impact", "service_access",
    "ptsd1", "ptsd2", "ptsd3", "ptsd4", "ptsd5"
]

for col in categorical_cols:
    print("\n---", col, "---")
    print(df[col].value_counts(dropna=False))

#Recheck missing table
missing_table = pd.DataFrame({
    'Missing Count': df.isnull().sum(),
    'Missing Percent': (df.isnull().sum() / len(df)) * 100
})

missing_table.sort_values(by='Missing Percent', ascending=False)

# Compute PHQ and GAD totals only when all required items are present
# min_count=2 prevents incomplete 2-item scales from being silently scored.
df["gad_total"] = df[["gad1", "gad2"]].sum(axis=1, min_count=2)
df["phq_total"] = df[["phq1", "phq2"]].sum(axis=1, min_count=2)

#PTSD item columns
ptsd_cols = ["ptsd1", "ptsd2", "ptsd3", "ptsd4", "ptsd5"]

# Inspect original PTSD responses before recoding
for col in ptsd_cols:
    print("\n---", col, "---")
    print(df[col].value_counts(dropna=False))

# Recode PTSD responses safely.
# Keep original text columns unchanged, then create clean and numeric versions.
ptsd_map = {
    "no": 0,
    "maybe": 1,
    "may be": 1,
    "yes": 2
}

for col in ptsd_cols:
    clean_col = col + "_clean"
    num_col = col + "_num"

    df[clean_col] = df[col].astype("string").str.strip().str.lower()
    df[clean_col] = df[clean_col].replace("may be", "maybe")
    df[num_col] = df[clean_col].map(ptsd_map)

# Compute PTSD total only from numeric PTSD item columns.
# min_count=5 means PTSD total is calculated only when all five items are present.
ptsd_num_cols = [col + "_num" for col in ptsd_cols]
df["ptsd_total"] = df[ptsd_num_cols].sum(axis=1, min_count=5)

# Check the PTSD recoding and total score
df[ptsd_cols + [col + "_clean" for col in ptsd_cols] + ptsd_num_cols + ["ptsd_total"]].head()

# Check missingness after corrected score construction
df[["phq_total", "gad_total", "ptsd_total"]].isnull().sum()

# Summary statistics for corrected scale totals
df[["phq_total", "gad_total", "ptsd_total"]].describe()

# Check final columns after preprocessing
df.columns.tolist()

score_outcomes = ['gad_total', 'phq_total', 'ptsd_total']

candidate_predictors = [
    'age',
    'gender',
    'education',
    'employment_status',
    'marital_status',
    'household_income',
    'resident_status',
    'region',
    'living_area',
    'financial_struggle',
    'bill_difficulty',
    'income_stability',
    'financial_stress',
    'healthcare_access',
    'housing_situation',
    'conflict_impact',
    'service_access'
]

for col in candidate_predictors:
    print('\n' + '='*50)
    print(col)
    print(df[col].value_counts(dropna=False))

"""##Grouping"""

df['gender_group'] = df['gender'].replace({'Prefer not to say': np.nan})
df['gender_group'].value_counts(dropna=False)

education_map = {
    'Primary (1-4)': 'High school',
    'Middle (4-8)': 'High school',
    'High(8-12)': 'High school',
    'Diploma': 'Higher education',
    'University Graduate( Bachelor)': 'Higher education',
    'Postgraduate( Masters , PHD)': 'Higher education'
}

df['education_group'] = df['education'].map(education_map)
df['education_group'].value_counts(dropna=False)

employment_map = {
    'Full-time': 'Employed',
    'Part-time': 'Employed',
    'Freelance': 'Employed',
    'Business owner': 'Employed',
    'Self-employed': 'Employed',
    'Student': 'Student',
    'unemployed but looking for work currently': 'Unemployed',
    'unemployed- Not Looking for Work': 'Unemployed',
    'Stay-at-home Parent': 'Unemployed',
    'Dependent': 'Unemployed',
    'Retired': 'Unemployed',
    'Other': 'Unemployed',
    'other': 'Unemployed',
    'lose job': 'Unemployed',
    "I haven't job since before conflict": 'Unemployed',
    'No job yet': 'Unemployed',
    'Stop education': 'Unemployed',
    'No job, no impact': 'Unemployed',
    'because of global crises, my stipends got reduced': 'Unemployed'

}

df['employment_group'] = df['employment_status'].map(employment_map)
df['employment_group'].value_counts(dropna=False)

income_map = {
    'I have no income currently': 'Low income',
    'Less than 300K ( less than 300,000 MMK)': 'Low income',
    '300K- 600K (300,000 - 600,000 MMK )': 'Low income',
    '600K-800K(600,000 - 800,000 MMK)': 'Middle income',
    '800K-1000K( 800,000 - 1,000,000 MMK)': 'Middle income',
    '1000K-2000K ( 1,000,000- 2,000,000 MMK)': 'High income',
    'More than 2000K (more than 2,000,000 MMK)': 'High income'
}

df['income_group'] = df['household_income'].map(income_map)
df['income_group'].value_counts(dropna=False)



financial_struggle_map = {
    'Never': 'Low',
    'Rarely': 'Low',
    'Sometimes': 'Moderate',
    'Often': 'High',
    'Very often': 'High'
}

df['financial_struggle_group'] = df['financial_struggle'].map(financial_struggle_map)
df['financial_struggle_group'].value_counts(dropna=False)

bill_difficulty_map = {
    'Not difficult at all.': 'Low',
    'Slightly difficult': 'Low',
    'Moderately difficult': 'Moderate',
    'Very difficult': 'High',
    'Extremely difficult': 'High'
}

df['bill_difficulty_group'] = df['bill_difficulty'].map(bill_difficulty_map)
df['bill_difficulty_group'].value_counts(dropna=False)

income_stability_map = {
    'Yes and Stable': 'Stable',
    'Yes but unstable': 'Unstable',
    'No stable income': 'Unstable',
    'No income at all': 'No income'
}

df['income_stability_group'] = df['income_stability'].map(income_stability_map)

financial_stress_map = {
    'Never': 'Low',
    'Rarely': 'Low',
    'Sometimes': 'Moderate',
    'Often': 'High',
    'Very often': 'High'
}

df['financial_stress_group'] = df['financial_stress'].map(financial_stress_map)
df['financial_stress_group'].value_counts(dropna=False)

healthcare_access_map = {
    'Yes and always': 'Has access',
    'Yes but only occasionally': 'Has access',
    'Rarely No': 'Limited/no access',
    'No': 'Limited/no access'
}

df['healthcare_access_group'] = df['healthcare_access'].map(healthcare_access_map)
df['healthcare_access_group'].value_counts(dropna=False)

housing_map = {
    'secure and stable': 'Stable housing',
    'Somewhat stable': 'Stable housing',
    'Unstable': 'Unstable housing',
    'At risk of losing housing': 'Unstable housing',
    'homeless and displaced': 'Unstable housing'
}

df['housing_group'] = df['housing_situation'].map(housing_map)
df['housing_group'].value_counts(dropna=False)

conflict_impact_map = {
    'No impact': 'No/Mild Impact',
    'Mild impact': 'No/Mild Impact',
    'Moderate impact': 'Moderate/Severe Impact',
    'Severe impact': 'Moderate/Severe Impact',
    'lose job': 'Other',
    "I haven't job since before conflict": 'Other',
    'No job yet': 'Other',
    'Stop education': 'Other',
    'No job, no impact': 'Other',
    'because of global crises, my stipends got reduced': 'Other'
}

df['conflict_impact_group'] = df['conflict_impact'].map(conflict_impact_map)
df['conflict_impact_group'].value_counts(dropna=False)

service_access_map = {
    'Very easy': 'Easy',
    'Easy': 'Easy',
    'Moderate': 'Moderate',
    'Hard': 'Hard',
    'Very Hard': 'Hard'
}

df['service_access_group'] = df['service_access'].map(service_access_map)
df['service_access_group'].value_counts(dropna=False)

grouped_vars = [
    'gender_group',
    'education_group',
    'employment_group',
    'income_group',
    'financial_struggle_group',
    'bill_difficulty_group',
    'income_stability_group',
    'financial_stress_group',
    'healthcare_access_group',
    'housing_group',
    'conflict_impact_group',
    'service_access_group'
]

for col in grouped_vars:
    print('\n' + '='*50)
    print(col)
    print(df[col].value_counts(dropna=False))

mapping_checks = {
    'gender_group': 'gender',
    'education_group': 'education',
    'employment_group': 'employment_status',
    'income_group': 'household_income',
    'financial_struggle_group': 'financial_struggle',
    'bill_difficulty_group': 'bill_difficulty',
    'income_stability_group': 'income_stability',
    'financial_stress_group': 'financial_stress',
    'healthcare_access_group': 'healthcare_access',
    'housing_group': 'housing_situation',
    'conflict_impact_group': 'conflict_impact',
    'service_access_group': 'service_access'
}

for new_col, old_col in mapping_checks.items():
    print('\n' + '='*60)
    print(f'{new_col} NaNs came from original {old_col}:')
    print(df.loc[df[new_col].isna(), old_col].value_counts(dropna=False))

df.shape

"""# Phase 3: Normality Checks

"""

from scipy import stats

score_outcomes = ['gad_total', 'phq_total', 'ptsd_total']

normality_results = []

for outcome in score_outcomes:
    data = df[outcome].dropna()

    shapiro_stat, shapiro_p = stats.shapiro(data)
    skewness = stats.skew(data)
    kurtosis = stats.kurtosis(data)

    normality_results.append({
        'outcome': outcome,
        'n': len(data),
        'shapiro_stat': shapiro_stat,
        'shapiro_p': shapiro_p,
        'skewness': skewness,
        'kurtosis': kurtosis
    })

normality_table = pd.DataFrame(normality_results)
normality_table

"""## Outlier Check"""

score_outcomes = ['gad_total', 'phq_total', 'ptsd_total']

outlier_summary = []

for col in score_outcomes:
    data = df[col].dropna()

    q1 = data.quantile(0.25)
    q3 = data.quantile(0.75)
    iqr = q3 - q1

    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr

    outliers = data[(data < lower_bound) | (data > upper_bound)]

    outlier_summary.append({
        'outcome': col,
        'n': len(data),
        'q1': q1,
        'q3': q3,
        'iqr': iqr,
        'lower_bound': lower_bound,
        'upper_bound': upper_bound,
        'outlier_count': len(outliers),
        'outlier_percent': len(outliers) / len(data) * 100
    })

outlier_table = pd.DataFrame(outlier_summary)
outlier_table

import matplotlib.pyplot as plt

for col in score_outcomes:
    plt.figure(figsize=(6, 4))
    plt.boxplot(df[col].dropna(), vert=False)
    plt.title(f'Boxplot of {col}')
    plt.xlabel(col)
    plt.show()

"""# Phase 4 : Inferential Analysis

# Tests: 2 GP Comparsions Using Welch T-Test
"""

from scipy import stats   # Gender
score_outcomes = ['gad_total', 'phq_total', 'ptsd_total']

gender_test_results = []

for outcome in score_outcomes:
    temp = df[[outcome, 'gender_group']].dropna()

    male = temp[temp['gender_group'] == 'Male'][outcome]
    female = temp[temp['gender_group'] == 'Female'][outcome]

    # t-test (always use Welch's t-test for robustness)
    t_stat, t_p = stats.ttest_ind(male, female, equal_var=False)

    # Mann-Whitney U robustness check
    u_stat, u_p = stats.mannwhitneyu(male, female, alternative='two-sided')

    # Cohen's d
    n1, n2 = len(male), len(female)
    mean1, mean2 = male.mean(), female.mean()
    sd1, sd2 = male.std(ddof=1), female.std(ddof=1)

    # Calculate pooled SD for Cohen's d, as ttest_ind with equal_var=False doesn't provide it directly
    # For Welch's t-test, it's more appropriate to use the individual standard deviations for effect size if sample sizes are very different, but pooled SD is common for reporting.
    # Using pooled standard deviation for Cohen's d for consistency with earlier approach. Alternatively, one might consider separate SDs.
    pooled_sd = np.sqrt(((n1 - 1) * sd1**2 + (n2 - 1) * sd2**2) / (n1 + n2 - 2))
    cohens_d = (mean1 - mean2) / pooled_sd

    gender_test_results.append({
        'outcome': outcome,
        'male_n': n1,
        'female_n': n2,
        'male_mean': round(mean1, 3),
        'female_mean': round(mean2, 3),
        'selected_test': 'Welch t-test',
        't_stat': round(t_stat, 3),
        't_p': round(t_p, 4),
        'mannwhitney_p': round(u_p, 4),
        'cohens_d': round(cohens_d, 3)
    })

gender_test_table = pd.DataFrame(gender_test_results)
gender_test_table

# Education Vs Mental Health
from scipy import stats

score_outcomes = ['gad_total', 'phq_total', 'ptsd_total']
predictor = 'education_group'

education_results = []

for outcome in score_outcomes:
    temp = df[[outcome, predictor]].dropna()

    groups = temp[predictor].unique()

    group1 = temp[temp[predictor] == groups[0]][outcome]
    group2 = temp[temp[predictor] == groups[1]][outcome]

    # t-test (always use Welch's t-test for robustness)
    t_stat, t_p = stats.ttest_ind(group1, group2, equal_var=False)

    # Mann-Whitney U
    u_stat, u_p = stats.mannwhitneyu(group1, group2, alternative='two-sided')

    # Cohen's d
    n1, n2 = len(group1), len(group2)
    mean1, mean2 = group1.mean(), group2.mean()
    sd1, sd2 = group1.std(ddof=1), group2.std(ddof=1)
    pooled_sd = np.sqrt(((n1 - 1)*sd1**2 + (n2 - 1)*sd2**2) / (n1 + n2 - 2))
    cohens_d = (mean1 - mean2) / pooled_sd

    education_results.append({
        'outcome': outcome,
        'group_1': groups[0],
        'group_1_n': n1,
        'group_1_mean': round(mean1, 3),
        'group_2': groups[1],
        'group_2_n': n2,
        'group_2_mean': round(mean2, 3),
        'selected_test': 'Welch t-test',
        't_stat': round(t_stat, 3),
        't_p': round(t_p, 4),
        'mannwhitney_p': round(u_p, 4),
        'cohens_d': round(cohens_d, 3)
    })

education_test_table = pd.DataFrame(education_results)
education_test_table

for outcome in score_outcomes:
    temp = df[[outcome, predictor]].dropna()

    plt.figure(figsize=(7, 5))
    temp.boxplot(column=outcome, by=predictor)
    plt.title(f'{outcome} by Education Group')
    plt.suptitle('')
    plt.xlabel('Education Group')
    plt.ylabel(outcome)
    plt.show()

from scipy import stats
import pandas as pd
import numpy as np

score_outcomes = ['gad_total', 'phq_total', 'ptsd_total']
predictor = 'education_group'

education_results = []

for outcome in score_outcomes:
    temp = df[[outcome, predictor]].dropna()

    groups = temp[predictor].dropna().unique()

    group1_name = groups[0]
    group2_name = groups[1]

    group1 = temp[temp[predictor] == group1_name][outcome]
    group2 = temp[temp[predictor] == group2_name][outcome]

    # t-test / Welch (always use Welch's t-test)
    t_stat, t_p = stats.ttest_ind(group1, group2, equal_var=False)

    # Mann-Whitney U
    u_stat, u_p = stats.mannwhitneyu(group1, group2, alternative='two-sided')

    # Means and SDs
    n1, n2 = len(group1), len(group2)
    mean1, mean2 = group1.mean(), group2.mean()
    sd1, sd2 = group1.std(ddof=1), group2.std(ddof=1)

    # Mean difference
    mean_diff = mean1 - mean2

    # Cohen's d
    pooled_sd = np.sqrt(((n1 - 1)*sd1**2 + (n2 - 1)*sd2**2) / (n1 + n2 - 2))
    cohens_d = mean_diff / pooled_sd

    # 95% CI for mean difference (using Welch's t-test calculation for CI)
    se_diff = np.sqrt((sd1**2/n1) + (sd2**2/n2))
    dfree = ((sd1**2/n1 + sd2**2/n2)**2) / (
        ((sd1**2/n1)**2 / (n1 - 1)) + ((sd2**2/n2)**2 / (n2 - 1))
    )

    ci_low, ci_high = stats.t.interval(
        confidence=0.95,
        df=dfree,
        loc=mean_diff,
        scale=se_diff
    )

    education_results.append({
        'outcome': outcome,
        'group_1': group1_name,
        'group_1_n': n1,
        'group_1_mean': round(mean1, 3),
        'group_2': group2_name,
        'group_2_n': n2,
        'group_2_mean': round(mean2, 3),
        'mean_diff_g1_minus_g2': round(mean_diff, 3),
        'ci_95_low': round(ci_low, 3),
        'ci_95_high': round(ci_high, 3),
        'selected_test': 'Welch t-test',
        't_stat': round(t_stat, 3),
        't_p': round(t_p, 4),
        'mannwhitney_p': round(u_p, 4),
        'cohens_d': round(cohens_d, 3)
    })

education_test_table = pd.DataFrame(education_results)
education_test_table

from scipy import stats
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

score_outcomes = ['gad_total', 'phq_total', 'ptsd_total']
predictor = 'living_area'

living_area_results = []

for outcome in score_outcomes:
    temp = df[[outcome, predictor]].dropna()

    groups = temp[predictor].dropna().unique()

    group1_name = groups[0]
    group2_name = groups[1]

    group1 = temp[temp[predictor] == group1_name][outcome]
    group2 = temp[temp[predictor] == group2_name][outcome]

    # t-test / Welch (always use Welch's t-test)
    t_stat, t_p = stats.ttest_ind(group1, group2, equal_var=False)

    # Mann-Whitney U
    u_stat, u_p = stats.mannwhitneyu(group1, group2, alternative='two-sided')

    # Means and SDs
    n1, n2 = len(group1), len(group2)
    mean1, mean2 = group1.mean(), group2.mean()
    sd1, sd2 = group1.std(ddof=1), group2.std(ddof=1)

    # Mean difference
    mean_diff = mean1 - mean2

    # Cohen's d
    pooled_sd = np.sqrt(((n1 - 1)*sd1**2 + (n2 - 1)*sd2**2) / (n1 + n2 - 2))
    cohens_d = mean_diff / pooled_sd

    # 95% CI for mean difference (using Welch's t-test calculation for CI)
    se_diff = np.sqrt((sd1**2/n1) + (sd2**2/n2))
    dfree = ((sd1**2/n1 + sd2**2/n2)**2) / (
        ((sd1**2/n1)**2 / (n1 - 1)) + ((sd2**2/n2)**2 / (n2 - 1))
    )

    ci_low, ci_high = stats.t.interval(
        confidence=0.95,
        df=dfree,
        loc=mean_diff,
        scale=se_diff
    )

    living_area_results.append({
        'outcome': outcome,
        'group_1': group1_name,
        'group_1_n': n1,
        'group_1_mean': round(mean1, 3),
        'group_2': group2_name,
        'group_2_n': n2,
        'group_2_mean': round(mean2, 3),
        'mean_diff_g1_minus_g2': round(mean_diff, 3),
        'ci_95_low': round(ci_low, 3),
        'ci_95_high': round(ci_high, 3),
        'selected_test': 'Welch t-test',
        't_stat': round(t_stat, 3),
        't_p': round(t_p, 4),
        'mannwhitney_p': round(u_p, 4),
        'cohens_d': round(cohens_d, 3)
    })

living_area_test_table = pd.DataFrame(living_area_results)
living_area_test_table

import matplotlib.pyplot as plt
from scipy import stats
import numpy as np

score_outcomes = ['gad_total', 'phq_total', 'ptsd_total']
predictor = 'living_area'

for outcome in score_outcomes:
    temp = df[[outcome, predictor]].dropna()

    summary = temp.groupby(predictor)[outcome].agg(['mean', 'count', 'std'])
    summary['se'] = summary['std'] / np.sqrt(summary['count'])
    summary['ci95'] = summary['se'] * stats.t.ppf(0.975, summary['count'] - 1)

    plt.figure(figsize=(7, 5))
    plt.errorbar(
        x=summary.index,
        y=summary['mean'],
        yerr=summary['ci95'],
        fmt='o',
        capsize=5
    )
    plt.title(f'Mean {outcome} by Living Area with 95% CI')
    plt.xlabel('Living Area')
    plt.ylabel(f'Mean {outcome}')
    plt.show()

score_outcomes = ['gad_total', 'phq_total', 'ptsd_total']
predictor = 'living_area'

for outcome in score_outcomes:
    temp = df[[outcome, predictor]].dropna()
    groups = temp[predictor].unique()

    plt.figure(figsize=(7, 5))

    for i, group in enumerate(groups):
        y = temp[temp[predictor] == group][outcome]
        x = np.random.normal(i + 1, 0.04, size=len(y))
        plt.scatter(x, y, alpha=0.5)

    plt.xticks(range(1, len(groups) + 1), groups)
    plt.title(f'{outcome} by Living Area')
    plt.xlabel('Living Area')
    plt.ylabel(outcome)
    plt.show()

from scipy import stats # Healthcare_access VS Mental Health

score_outcomes = ['gad_total', 'phq_total', 'ptsd_total']
predictor = 'healthcare_access_group'

two_group_results = []

for outcome in score_outcomes:
    temp = df[[outcome, predictor]].dropna()

    groups = temp[predictor].dropna().unique()

    group1_name = groups[0]
    group2_name = groups[1]

    group1 = temp[temp[predictor] == group1_name][outcome]
    group2 = temp[temp[predictor] == group2_name][outcome]

    # t-test / Welch (always use Welch's t-test)
    t_stat, t_p = stats.ttest_ind(group1, group2, equal_var=False)

    # Mann-Whitney U
    u_stat, u_p = stats.mannwhitneyu(group1, group2, alternative='two-sided')

    # Means and SDs
    n1, n2 = len(group1), len(group2)
    mean1, mean2 = group1.mean(), group2.mean()
    sd1, sd2 = group1.std(ddof=1), group2.std(ddof=1)

    # Mean difference
    mean_diff = mean1 - mean2

    # Cohen's d
    pooled_sd = np.sqrt(((n1 - 1)*sd1**2 + (n2 - 1)*sd2**2) / (n1 + n2 - 2))
    cohens_d = mean_diff / pooled_sd

    # 95% CI for mean difference (using Welch's t-test calculation for CI)
    se_diff = np.sqrt((sd1**2/n1) + (sd2**2/n2))
    dfree = ((sd1**2/n1 + sd2**2/n2)**2) / (
        ((sd1**2/n1)**2 / (n1 - 1)) + ((sd2**2/n2)**2 / (n2 - 1))
    )

    ci_low, ci_high = stats.t.interval(
        confidence=0.95,
        df=dfree,
        loc=mean_diff,
        scale=se_diff
    )

    two_group_results.append({
        'outcome': outcome,
        'group_1': group1_name,
        'group_1_n': n1,
        'group_1_mean': round(mean1, 3),
        'group_2': group2_name,
        'group_2_n': n2,
        'group_2_mean': round(mean2, 3),
        'mean_diff_g1_minus_g2': round(mean_diff, 3),
        'ci_95_low': round(ci_low, 3),
        'ci_95_high': round(ci_high, 3),
        'selected_test': 'Welch t-test',
        't_stat': round(t_stat, 3),
        't_p': round(t_p, 4),
        'mannwhitney_p': round(u_p, 4),
        'cohens_d': round(cohens_d, 3)
    })

healthcare_access_test_table = pd.DataFrame(two_group_results)
healthcare_access_test_table

for outcome in score_outcomes:
    temp = df[[outcome, predictor]].dropna()

    plt.figure(figsize=(7, 5))
    temp.boxplot(column=outcome, by=predictor)
    plt.title(f'{outcome} by Healthcare Access Group')
    plt.suptitle('')
    plt.xlabel('Healthcare Access Group')
    plt.ylabel(outcome)
    plt.xticks(rotation=15)
    plt.show()

for outcome in score_outcomes:          # mean plot
    temp = df[[outcome, predictor]].dropna()

    summary = temp.groupby(predictor)[outcome].agg(['mean', 'count', 'std'])
    summary['se'] = summary['std'] / np.sqrt(summary['count'])
    summary['ci95'] = summary['se'] * stats.t.ppf(0.975, summary['count'] - 1)

    plt.figure(figsize=(7, 5))
    plt.errorbar(
        x=summary.index,
        y=summary['mean'],
        yerr=summary['ci95'],
        fmt='o',
        capsize=5
    )
    plt.title(f'Mean {outcome} by Healthcare Access with 95% CI')
    plt.xlabel('Healthcare Access Group')
    plt.ylabel(f'Mean {outcome}')
    plt.xticks(rotation=15)
    plt.show()

# Housing Status Vs Menatal Health
from scipy import stats

score_outcomes = ['gad_total', 'phq_total', 'ptsd_total']
predictor = 'housing_group'

housing_results = []

for outcome in score_outcomes:
    temp = df[[outcome, predictor]].dropna()

    groups = temp[predictor].dropna().unique()

    group1_name = groups[0]
    group2_name = groups[1]

    group1 = temp[temp[predictor] == group1_name][outcome]
    group2 = temp[temp[predictor] == group2_name][outcome]

    # t-test / Welch (always use Welch's t-test)
    t_stat, t_p = stats.ttest_ind(group1, group2, equal_var=False)

    # Mann-Whitney U
    u_stat, u_p = stats.mannwhitneyu(group1, group2, alternative='two-sided')

    # Means and SDs
    n1, n2 = len(group1), len(group2)
    mean1, mean2 = group1.mean(), group2.mean()
    sd1, sd2 = group1.std(ddof=1), group2.std(ddof=1)

    # Mean difference
    mean_diff = mean1 - mean2

    # Cohen's d
    pooled_sd = np.sqrt(((n1 - 1)*sd1**2 + (n2 - 1)*sd2**2) / (n1 + n2 - 2))
    cohens_d = mean_diff / pooled_sd

    # 95% CI for mean difference (using Welch's t-test calculation for CI)
    se_diff = np.sqrt((sd1**2/n1) + (sd2**2/n2))
    dfree = ((sd1**2/n1 + sd2**2/n2)**2) / (
        ((sd1**2/n1)**2 / (n1 - 1)) + ((sd2**2/n2)**2 / (n2 - 1))
    )

    ci_low, ci_high = stats.t.interval(
        confidence=0.95,
        df=dfree,
        loc=mean_diff,
        scale=se_diff
    )

    housing_results.append({
        'outcome': outcome,
        'group_1': group1_name,
        'group_1_n': n1,
        'group_1_mean': round(mean1, 3),
        'group_2': group2_name,
        'group_2_n': n2,
        'group_2_mean': round(mean2, 3),
        'mean_diff_g1_minus_g2': round(mean_diff, 3),
        'ci_95_low': round(ci_low, 3),
        'ci_95_high': round(ci_high, 3),
        'selected_test': 'Welch t-test',
        't_stat': round(t_stat, 3),
        't_p': round(t_p, 4),
        'mannwhitney_p': round(u_p, 4),
        'cohens_d': round(cohens_d, 3)
    })

housing_test_table = pd.DataFrame(housing_results)
housing_test_table

for outcome in score_outcomes:
    temp = df[[outcome, predictor]].dropna()

    plt.figure(figsize=(7, 5))
    temp.boxplot(column=outcome, by=predictor)
    plt.title(f'{outcome} by Housing Group')
    plt.suptitle('')
    plt.xlabel('Housing Group')
    plt.ylabel(outcome)
    plt.xticks(rotation=15)
    plt.show()

# Conflict_impact Vs Mental Health
df_conflict = df[df['conflict_impact_group'].isin([
    'No/Mild Impact',
    'Moderate/Severe Impact'
])].copy()


score_outcomes = ['gad_total', 'phq_total', 'ptsd_total']
predictor = 'conflict_impact_group'

# Keep only the two meaningful groups
df_conflict = df[df[predictor].isin([
    'No/Mild Impact',
    'Moderate/Severe Impact'
])].copy()

conflict_results = []

for outcome in score_outcomes:
    temp = df_conflict[[outcome, predictor]].dropna()

    groups = temp[predictor].dropna().unique()

    group1_name = groups[0]
    group2_name = groups[1]

    group1 = temp[temp[predictor] == group1_name][outcome]
    group2 = temp[temp[predictor] == group2_name][outcome]

    # Welch t-test
    t_stat, t_p = stats.ttest_ind(group1, group2, equal_var=False)

    # Mann-Whitney U robustness check
    u_stat, u_p = stats.mannwhitneyu(group1, group2, alternative='two-sided')

    # Means and SDs
    n1, n2 = len(group1), len(group2)
    mean1, mean2 = group1.mean(), group2.mean()
    sd1, sd2 = group1.std(ddof=1), group2.std(ddof=1)

    # Mean difference
    mean_diff = mean1 - mean2

    # Cohen's d
    pooled_sd = np.sqrt(
        ((n1 - 1) * sd1**2 + (n2 - 1) * sd2**2) / (n1 + n2 - 2)
    )
    cohens_d = mean_diff / pooled_sd

    # 95% CI for mean difference using Welch calculation
    se_diff = np.sqrt((sd1**2 / n1) + (sd2**2 / n2))

    dfree = ((sd1**2 / n1 + sd2**2 / n2) ** 2) / (
        ((sd1**2 / n1) ** 2 / (n1 - 1)) +
        ((sd2**2 / n2) ** 2 / (n2 - 1))
    )

    ci_low, ci_high = stats.t.interval(
        confidence=0.95,
        df=dfree,
        loc=mean_diff,
        scale=se_diff
    )

    conflict_results.append({
        'outcome': outcome,
        'group_1': group1_name,
        'group_1_n': n1,
        'group_1_mean': round(mean1, 3),
        'group_2': group2_name,
        'group_2_n': n2,
        'group_2_mean': round(mean2, 3),
        'mean_diff_g1_minus_g2': round(mean_diff, 3),
        'ci_95_low': round(ci_low, 3),
        'ci_95_high': round(ci_high, 3),
        'selected_test': 'Welch t-test',
        't_stat': round(t_stat, 3),
        't_p': round(t_p, 4),
        'mannwhitney_p': round(u_p, 4),
        'cohens_d': round(cohens_d, 3)
    })

conflict_test_table = pd.DataFrame(conflict_results)
conflict_test_table

for outcome in score_outcomes:     # Mean Plot with 95% CI
    temp = df_conflict[[outcome, predictor]].dropna()

    summary = temp.groupby(predictor)[outcome].agg(['mean', 'count', 'std'])
    summary['se'] = summary['std'] / np.sqrt(summary['count'])
    summary['ci95'] = summary['se'] * stats.t.ppf(0.975, summary['count'] - 1)

    plt.figure(figsize=(7, 5))
    plt.errorbar(
        x=summary.index,
        y=summary['mean'],
        yerr=summary['ci95'],
        fmt='o',
        capsize=5
    )
    plt.title(f'Mean {outcome} by Conflict Impact Group with 95% CI')
    plt.xlabel('Conflict Impact Group')
    plt.ylabel(f'Mean {outcome}')
    plt.xticks(rotation=15)
    plt.show()

welch_t_test_summary_results = []

# Gender vs Mental Health
for index, row in gender_test_table.iterrows():
    welch_t_test_summary_results.append({
        'Predictor': 'gender_group',
        'Outcome': row['outcome'],
        'Group_1': row['male_mean'],
        'Group_2': row['female_mean'],
        't_statistic': row['t_stat'],
        'p_value': row['t_p'],
        'Cohen_d': row['cohens_d']
    })

# Education vs Mental Health
for index, row in education_test_table.iterrows():
    welch_t_test_summary_results.append({
        'Predictor': 'education_group',
        'Outcome': row['outcome'],
        'Group_1': row['group_1_mean'],
        'Group_2': row['group_2_mean'],
        't_statistic': row['t_stat'],
        'p_value': row['t_p'],
        'Cohen_d': row['cohens_d']
    })

# Living Area vs Mental Health
for index, row in living_area_test_table.iterrows():
    welch_t_test_summary_results.append({
        'Predictor': 'living_area',
        'Outcome': row['outcome'],
        'Group_1': row['group_1_mean'],
        'Group_2': row['group_2_mean'],
        't_statistic': row['t_stat'],
        'p_value': row['t_p'],
        'Cohen_d': row['cohens_d']
    })

# Healthcare Access vs Mental Health
for index, row in healthcare_access_test_table.iterrows():
    welch_t_test_summary_results.append({
        'Predictor': 'healthcare_access_group',
        'Outcome': row['outcome'],
        'Group_1': row['group_1_mean'],
        'Group_2': row['group_2_mean'],
        't_statistic': row['t_stat'],
        'p_value': row['t_p'],
        'Cohen_d': row['cohens_d']
    })

# Housing Status vs Mental Health
for index, row in housing_test_table.iterrows():
    welch_t_test_summary_results.append({
        'Predictor': 'housing_group',
        'Outcome': row['outcome'],
        'Group_1': row['group_1_mean'],
        'Group_2': row['group_2_mean'],
        't_statistic': row['t_stat'],
        'p_value': row['t_p'],
        'Cohen_d': row['cohens_d']
    })

# Conflict Impact vs Mental Health
for index, row in conflict_test_table.iterrows():
    welch_t_test_summary_results.append({
        'Predictor': 'conflict_impact_group',
        'Outcome': row['outcome'],
        'Group_1': row['group_1_mean'],
        'Group_2': row['group_2_mean'],
        't_statistic': row['t_stat'],
        'p_value': row['t_p'],
        'Cohen_d': row['cohens_d']
    })

comparative_welch_t_test_summary = pd.DataFrame(welch_t_test_summary_results)
display(comparative_welch_t_test_summary.round(4))

"""## Key findings for each predictor:

*   **Gender:**
    *   `phq_total`: There is a statistically significant difference in PHQ scores between genders (p-value = 0.0287, Cohen's d = 0.258), with males having a slightly higher mean PHQ score (7.272) compared to females (6.526).
    *   No significant differences were found for `gad_total` or `ptsd_total`.

*   **Education Group:**
    *   `gad_total`: There is a statistically significant difference in GAD scores (p-value = 0.0184, Cohen's d = -0.286), indicating that individuals with High School education (mean = 7.481) tend to have higher GAD scores than those with Higher Education (mean = 6.706).
    *   No significant differences were observed for `phq_total` or `ptsd_total`.

*   **Living Area:**
    *   `gad_total`: Rural areas (mean = 7.464) show significantly higher GAD scores than urban areas (mean = 6.744) (p-value = 0.0273, Cohen's d = 0.266).
    *   `ptsd_total`: Rural areas (mean = 5.916) also exhibit significantly higher PTSD scores compared to urban areas (mean = 4.325) (p-value = 0.0002, Cohen's d = 0.459). This suggests a moderate effect.
    *   `phq_total`: Not statistically significant at the 0.05 level (p-value = 0.0804).

*   **Healthcare Access Group:**
    *   Significant differences were found across all mental health outcomes, with `Limited/no access` groups consistently reporting higher scores.
    *   `gad_total`: Those with Limited/no access (mean = 8.028) have significantly higher GAD scores than those with Has access (mean = 6.629) (p-value = 0.0002, Cohen's d = -0.525), a moderate effect.
    *   `phq_total`: Similarly, Limited/no access (mean = 7.889) shows higher PHQ scores than Has access (mean = 6.632) (p-value = 0.0010, Cohen's d = -0.434), a moderate effect.
    *   `ptsd_total`: Limited/no access (mean = 5.900) also leads to significantly higher PTSD scores compared to Has access (mean = 4.433) (p-value = 0.0022, Cohen's d = -0.422), a moderate effect.

*   **Housing Group:**
    *   Significant differences are present for all outcomes, with `Unstable housing` groups consistently showing higher distress.
    *   `gad_total`: Unstable housing (mean = 8.321) is associated with significantly higher GAD scores than Stable housing (mean = 6.212) (p-value = 0.0000, Cohen's d = -0.834), a large effect.
    *   `phq_total`: Unstable housing (mean = 7.855) also shows significantly higher PHQ scores than Stable housing (mean = 6.452) (p-value = 0.0001, Cohen's d = -0.491), a moderate effect.
    *   `ptsd_total`: Unstable housing (mean = 6.189) leads to significantly higher PTSD scores than Stable housing (mean = 4.120) (p-value = 0.0000, Cohen's d = -0.610), a moderate to large effect.

*   **Conflict Impact Group:**
    *   Significant differences were found for all mental health outcomes.
    *   `gad_total`: Individuals experiencing `Moderate/Severe Impact` from conflict (mean = 7.426) report significantly higher GAD scores than those with `No/Mild Impact` (mean = 5.338) (p-value = 0.0000, Cohen's d = -0.818), indicating a large effect.
    *   `phq_total`: Moderate/Severe Impact (mean = 7.229) also correlates with higher PHQ scores than No/Mild Impact (mean = 6.013) (p-value = 0.0020, Cohen's d = -0.428), a moderate effect.
    *   `ptsd_total`: Moderate/Severe Impact (mean = 5.295) results in significantly higher PTSD scores compared to No/Mild Impact (mean = 3.205) (p-value = 0.0000, Cohen's d = -0.614), a moderate to large effect.

# Tests: Correlation_Tests
"""

# Age Vs Mental Health
#Pearson correlation and Spearman correlation
from scipy import stats

score_outcomes = ['gad_total', 'phq_total', 'ptsd_total']

age_corr_results = []

for outcome in score_outcomes:
    temp = df[['age', outcome]].dropna()

    # Pearson correlation
    pearson_r, pearson_p = stats.pearsonr(temp['age'], temp[outcome])

    # Spearman correlation
    spearman_rho, spearman_p = stats.spearmanr(temp['age'], temp[outcome])

    age_corr_results.append({
        'outcome': outcome,
        'n': len(temp),
        'pearson_r': round(pearson_r, 3),
        'pearson_p': round(pearson_p, 4),
        'spearman_rho': round(spearman_rho, 3),
        'spearman_p': round(spearman_p, 4)
    })

age_corr_table = pd.DataFrame(age_corr_results)
age_corr_table

for outcome in score_outcomes:
    temp = df[['age', outcome]].dropna()

    plt.figure(figsize=(6, 4))
    plt.scatter(temp['age'], temp[outcome], alpha=0.6)
    plt.xlabel('Age')
    plt.ylabel(outcome)
    plt.title(f'Age vs {outcome}')
    plt.show()

score_outcomes = ['gad_total', 'phq_total', 'ptsd_total']

for outcome in score_outcomes:
    temp = df[['age', outcome]].dropna()

    x = temp['age']
    y = temp[outcome]

    # Linear trend line
    slope, intercept = np.polyfit(x, y, 1)
    trend_line = slope * x + intercept

    plt.figure(figsize=(7, 5))
    plt.scatter(x, y, alpha=0.6)
    plt.plot(x, trend_line)
    plt.xlabel('Age')
    plt.ylabel(outcome)
    plt.title(f'Age vs {outcome}')
    plt.show()

# Mental health scores with each other
mental_health_scores = ['gad_total', 'phq_total', 'ptsd_total']

corr_results = []

for i in range(len(mental_health_scores)):
    for j in range(i + 1, len(mental_health_scores)):
        var1 = mental_health_scores[i]
        var2 = mental_health_scores[j]

        temp = df[[var1, var2]].dropna()

        pearson_r, pearson_p = stats.pearsonr(temp[var1], temp[var2])
        spearman_rho, spearman_p = stats.spearmanr(temp[var1], temp[var2])

        corr_results.append({
            'variable_1': var1,
            'variable_2': var2,
            'n': len(temp),
            'pearson_r': round(pearson_r, 3),
            'pearson_p': round(pearson_p, 4),
            'spearman_rho': round(spearman_rho, 3),
            'spearman_p': round(spearman_p, 4)
        })

mental_health_corr_table = pd.DataFrame(corr_results)
mental_health_corr_table

corr_matrix = df[mental_health_scores].corr(method='spearman')

plt.figure(figsize=(6, 5))
plt.imshow(corr_matrix)
plt.colorbar(label='Spearman correlation')

plt.xticks(range(len(mental_health_scores)), mental_health_scores, rotation=45)
plt.yticks(range(len(mental_health_scores)), mental_health_scores)

for i in range(len(mental_health_scores)):
    for j in range(len(mental_health_scores)):
        plt.text(
            j, i,
            round(corr_matrix.iloc[i, j], 2),
            ha='center',
            va='center'
        )

plt.title('Spearman Correlation Heatmap of Mental Health Scores')
plt.tight_layout()
plt.show()

# Ordinal socioeconomic variables vs mental health
from scipy import stats
import pandas as pd

score_outcomes = ['gad_total', 'phq_total', 'ptsd_total']

ordinal_maps = {
    'income_group': {
        'Low income': 1,
        'Middle income': 2,
        'High income': 3
    },
    'financial_struggle_group': {
        'Low': 1,
        'Moderate': 2,
        'High': 3
    },
    'bill_difficulty_group': {
        'Low': 1,
        'Moderate': 2,
        'High': 3
    },
    'income_stability_group': {
        'Stable': 1,
        'Unstable': 2,
        'No income': 3
    },
    'financial_stress_group': {
        'Low': 1,
        'Moderate': 2,
        'High': 3
    },
    'conflict_impact_group': {
        'No/Mild Impact': 1,  # Corrected mapping
        'Moderate/Severe Impact': 2 # Corrected mapping
    },
    'service_access_group': {
        'Easy': 1,
        'Moderate': 2,
        'Hard': 3
    }
}

ordinal_corr_results = []

for predictor, mapping in ordinal_maps.items():
    numeric_col = predictor + '_num'
    df[numeric_col] = df[predictor].map(mapping)

    for outcome in score_outcomes:
        temp = df[[numeric_col, outcome]].dropna()

        # Only calculate correlation if there are enough data points
        if len(temp) > 1: # Spearmanr requires at least 2 observations
            rho, p_value = stats.spearmanr(temp[numeric_col], temp[outcome])

            ordinal_corr_results.append({
                'predictor': predictor,
                'outcome': outcome,
                'n': len(temp),
                'spearman_rho': round(rho, 3),
                'spearman_p': round(p_value, 4)
            })
        else:
            # Append NaN results if not enough data for correlation
            ordinal_corr_results.append({
                'predictor': predictor,
                'outcome': outcome,
                'n': len(temp),
                'spearman_rho': np.nan,
                'spearman_p': np.nan
            })

ordinal_corr_table = pd.DataFrame(ordinal_corr_results)
ordinal_corr_table

heatmap_data = ordinal_corr_table.pivot(
    index='predictor',
    columns='outcome',
    values='spearman_rho'
)

plt.figure(figsize=(8, 6))
plt.imshow(heatmap_data)
plt.colorbar(label='Spearman rho')

plt.xticks(range(len(heatmap_data.columns)), heatmap_data.columns, rotation=45)
plt.yticks(range(len(heatmap_data.index)), heatmap_data.index)

for i in range(len(heatmap_data.index)):
    for j in range(len(heatmap_data.columns)):
        plt.text(
            j, i,
            round(heatmap_data.iloc[i, j], 2),
            ha='center',
            va='center'
        )

plt.title('Ordinal Socioeconomic Variables vs Mental Health Scores')
plt.tight_layout()
plt.show()

df['conflict_impact_group'].value_counts(dropna=False)

correlation_summary = pd.concat([age_corr_table, mental_health_corr_table, ordinal_corr_table])

# Reset index for a cleaner look if desired
correlation_summary = correlation_summary.reset_index(drop=True)

print("\nSummary of Correlation Tests:")
display(correlation_summary.round(4))

"""## Key Findings from Correlation Tests:
Age vs. Mental Health Scores:

 *GAD Total: There is a small but significant negative correlation between age and GAD total scores (Pearson r = -0.172, p < 0.01; Spearman rho = -0.128, p < 0.05), suggesting that as age increases, GAD scores tend to slightly decrease.
* PHQ Total: A small but significant negative correlation exists between age and PHQ total scores (Pearson r = -0.140, p < 0.05; Spearman rho = -0.145, p < 0.05), indicating a slight decrease in PHQ scores with increasing age.
* PTSD Total: A moderate and highly significant negative correlation was found between age and PTSD total scores (Pearson r = -0.224, p < 0.001; Spearman rho = -0.221, p < 0.001), suggesting that younger individuals tend to report higher PTSD scores.
* Mental Health Scores with Each Other:

* GAD Total and PHQ Total: There is a moderate, highly significant positive correlation between GAD total and PHQ total scores (Pearson r = 0.345, p < 0.001; Spearman rho = 0.340, p < 0.001). This indicates that individuals with higher GAD scores also tend to have higher PHQ scores.
* GAD Total and PTSD Total: A strong, highly significant positive correlation exists between GAD total and PTSD total scores (Pearson r = 0.498, p < 0.001; Spearman rho = 0.496, p < 0.001).

This suggests a strong relationship where higher GAD scores are associated with higher PTSD scores.
* PHQ Total and PTSD Total: A small to moderate, highly significant positive correlation was observed between PHQ total and PTSD total scores (Pearson r = 0.274, p < 0.001; Spearman rho = 0.269, p < 0.001). This indicates that higher PHQ scores are related to higher PTSD scores.
* Ordinal Socioeconomic Variables vs. Mental Health Scores (Spearman's Rho):

* Income Group: Shows significant negative correlations with all mental health outcomes (rho values around -0.26 to -0.36, all p < 0.001), meaning lower income is associated with higher mental health distress.
* Financial Struggle, Bill Difficulty, Financial Stress: All show significant positive correlations with all mental health outcomes (rho values ranging from 0.18 to 0.49, all p < 0.01). This consistently indicates that greater financial struggle, difficulty with bills, and stress are associated with higher mental health distress.
* Income Stability Group: Shows significant positive correlations with all mental health outcomes (rho values around 0.16 to 0.28, all p < 0.01), suggesting that less stable income is associated with higher distress.
Conflict Impact Group: Shows significant positive correlations with all mental health outcomes (rho values around 0.19 to 0.34, all p < 0.001), indicating that greater conflict impact is associated with higher mental health distress.
* Service Access Group: Shows significant positive correlations with all mental health outcomes (rho values around 0.18 to 0.25, all p < 0.01), suggesting that harder access to services is associated with higher mental health distress.
* In summary, mental health scores are positively correlated with each other, and age is negatively correlated with mental health distress. Socioeconomic factors like income, financial stability, and access to services show significant correlations with mental health outcomes, generally indicating that adverse socioeconomic conditions are linked to higher levels of mental health distress.

# **Tests: ANOVA**
"""

# Employment GP Vs Mental Health Scores
score_outcomes = ['gad_total', 'phq_total', 'ptsd_total']
predictor = 'employment_group'

anova_results = []

for outcome in score_outcomes:
    temp = df[[outcome, predictor]].dropna()

    groups = [
        group[outcome].values
        for name, group in temp.groupby(predictor)
    ]

    group_summary = temp.groupby(predictor)[outcome].agg(['count', 'mean', 'std']).reset_index()

    # Levene's test
    levene_stat, levene_p = stats.levene(*groups)

    # One-way ANOVA
    f_stat, anova_p = stats.f_oneway(*groups)

    # Kruskal-Wallis
    h_stat, kruskal_p = stats.kruskal(*groups)

    # Eta-squared
    grand_mean = temp[outcome].mean()
    ss_between = sum(
        len(group[outcome]) * (group[outcome].mean() - grand_mean) ** 2
        for name, group in temp.groupby(predictor)
    )
    ss_total = sum((temp[outcome] - grand_mean) ** 2)
    eta_squared = ss_between / ss_total

    anova_results.append({
        'predictor': predictor,
        'outcome': outcome,
        'n': len(temp),
        'groups': temp[predictor].nunique(),
        'levene_p': round(levene_p, 4),
        'anova_f': round(f_stat, 3),
        'anova_p': round(anova_p, 4),
        'kruskal_h': round(h_stat, 3),
        'kruskal_p': round(kruskal_p, 4),
        'eta_squared': round(eta_squared, 3),
        'group_summary': group_summary[[predictor, 'count', 'mean']].to_dict('records')
    })

employment_anova_table = pd.DataFrame(anova_results)
employment_anova_table

for outcome in score_outcomes:
    temp = df[[outcome, predictor]].dropna()

    plt.figure(figsize=(8, 5))
    temp.boxplot(column=outcome, by=predictor)
    plt.title(f'{outcome} by Employment Group')
    plt.suptitle('')
    plt.xlabel('Employment Group')
    plt.ylabel(outcome)
    plt.xticks(rotation=20)
    plt.show()

from statsmodels.stats.multicomp import pairwise_tukeyhsd

temp = df[['gad_total', 'employment_group']].dropna()

tukey_gad_employment = pairwise_tukeyhsd(
    endog=temp['gad_total'],
    groups=temp['employment_group'],
    alpha=0.05
)

print(tukey_gad_employment)

score_outcomes = ['gad_total', 'phq_total', 'ptsd_total']
predictor = 'income_group'

income_welch_results = []

for outcome in score_outcomes:
    temp = df[[outcome, predictor]].dropna()

    # Welch ANOVA
    welch = pg.welch_anova(
        data=temp,
        dv=outcome,
        between=predictor
    )

    # Kruskal-Wallis robustness check
    groups = [
        group[outcome].values
        for name, group in temp.groupby(predictor)
    ]

    h_stat, kruskal_p = stats.kruskal(*groups)

    # Group summary
    group_summary = temp.groupby(predictor)[outcome].agg(
        ['count', 'mean', 'std']
    ).reset_index()

    income_welch_results.append({
        'predictor': predictor,
        'outcome': outcome,
        'n': len(temp),
        'groups': temp[predictor].nunique(),
        'welch_F': round(welch.loc[0, 'F'], 3),
        'welch_p': round(welch.loc[0, 'p_unc'], 4), # Corrected 'p-unc' to 'p_unc'
        'welch_np2': round(welch.loc[0, 'np2'], 3),
        'kruskal_H': round(h_stat, 3),
        'kruskal_p': round(kruskal_p, 4),
        'group_summary': group_summary[[predictor, 'count', 'mean']].to_dict('records')
    })

income_welch_table = pd.DataFrame(income_welch_results)
income_welch_table

for outcome in score_outcomes: # post-hoc for income
    temp = df[[outcome, predictor]].dropna()

    welch = pg.welch_anova(
        data=temp,
        dv=outcome,
        between=predictor
    )

    p_value = welch.loc[0, 'p_unc'] # Corrected 'p-unc' to 'p_unc'

    if p_value < 0.05:
        print('\n' + '='*60)
        print(f'Games-Howell post-hoc for {outcome}')

        gh = pg.pairwise_gameshowell(
            data=temp,
            dv=outcome,
            between=predictor
        )

        print(gh.to_string())

for outcome in score_outcomes:
    temp = df[[outcome, predictor]].dropna()

    summary = temp.groupby(predictor)[outcome].agg(['mean', 'count', 'std'])
    summary['se'] = summary['std'] / np.sqrt(summary['count'])
    summary['ci95'] = summary['se'] * stats.t.ppf(0.975, summary['count'] - 1)

    plt.figure(figsize=(8, 5))
    plt.errorbar(
        x=summary.index,
        y=summary['mean'],
        yerr=summary['ci95'],
        fmt='o',
        capsize=5
    )
    plt.title(f'Mean {outcome} by Income Group with 95% CI')
    plt.xlabel('Income Group')
    plt.ylabel(f'Mean {outcome}')
    plt.xticks(rotation=20)
    plt.show()

import pandas as pd
import numpy as np
import pingouin as pg
from scipy import stats
import matplotlib.pyplot as plt

score_outcomes = ['gad_total', 'phq_total', 'ptsd_total']
predictor = 'financial_stress_group'

financial_stress_results = []

for outcome in score_outcomes:
    temp = df[[outcome, predictor]].dropna()

    # Welch ANOVA
    welch = pg.welch_anova(
        data=temp,
        dv=outcome,
        between=predictor
    )

    # Kruskal-Wallis robustness check
    groups = [
        group[outcome].values
        for name, group in temp.groupby(predictor)
    ]

    h_stat, kruskal_p = stats.kruskal(*groups)

    # Group summary
    group_summary = temp.groupby(predictor)[outcome].agg(
        ['count', 'mean', 'std']
    ).reset_index()

    financial_stress_results.append({
        'predictor': predictor,
        'outcome': outcome,
        'n': len(temp),
        'groups': temp[predictor].nunique(),
        'welch_F': round(welch.loc[0, 'F'], 3),
        'welch_p': round(welch.loc[0, 'p_unc'], 4),
        'welch_np2': round(welch.loc[0, 'np2'], 3),
        'kruskal_H': round(h_stat, 3),
        'kruskal_p': round(kruskal_p, 4),
        'group_summary': group_summary[[predictor, 'count', 'mean']].to_dict('records')
    })

financial_stress_welch_table = pd.DataFrame(financial_stress_results)
financial_stress_welch_table

for outcome in score_outcomes:
    temp = df[[outcome, predictor]].dropna()

    welch = pg.welch_anova(
        data=temp,
        dv=outcome,
        between=predictor
    )

    p_value = welch.loc[0, 'p_unc']

    if p_value < 0.05:
        print('\n' + '='*60)
        print(f'Games-Howell post-hoc for {outcome}')

        gh = pg.pairwise_gameshowell(
            data=temp,
            dv=outcome,
            between=predictor
        )

        display(gh)

import pandas as pd
import numpy as np
import pingouin as pg
from scipy import stats
import matplotlib.pyplot as plt

score_outcomes = ['gad_total', 'phq_total', 'ptsd_total']
predictor = 'financial_struggle_group'

financial_struggle_results = []

for outcome in score_outcomes:
    temp = df[[outcome, predictor]].dropna()

    # Welch ANOVA
    welch = pg.welch_anova(
        data=temp,
        dv=outcome,
        between=predictor
    )

    # Detect p-value column safely
    if 'p_unc' in welch.columns: # Fixed: changed 'p-unc' to 'p_unc'
        p_col = 'p_unc'
    elif 'pval' in welch.columns:
        p_col = 'pval'
    elif 'p' in welch.columns:
        p_col = 'p'
    else:
        print(welch.columns)
        raise KeyError("Could not find p-value column.")

    # Kruskal-Wallis robustness check
    groups = [
        group[outcome].values
        for name, group in temp.groupby(predictor)
    ]

    h_stat, kruskal_p = stats.kruskal(*groups)

    # Group summary
    group_summary = temp.groupby(predictor)[outcome].agg(
        ['count', 'mean', 'std']
    ).reset_index()

    financial_struggle_results.append({
        'predictor': predictor,
        'outcome': outcome,
        'n': len(temp),
        'groups': temp[predictor].nunique(),
        'welch_F': round(welch.loc[0, 'F'], 3),
        'welch_p': round(welch.loc[0, p_col], 4),
        'welch_np2': round(welch.loc[0, 'np2'], 3) if 'np2' in welch.columns else np.nan,
        'kruskal_H': round(h_stat, 3),
        'kruskal_p': round(kruskal_p, 4),
        'group_summary': group_summary[[predictor, 'count', 'mean']].to_dict('records')
    })

financial_struggle_welch_table = pd.DataFrame(financial_struggle_results)
financial_struggle_welch_table

for outcome in score_outcomes:
    temp = df[[outcome, predictor]].dropna()

    welch = pg.welch_anova(
        data=temp,
        dv=outcome,
        between=predictor
    )

    if 'p_unc' in welch.columns:
        p_col = 'p_unc'
    elif 'pval' in welch.columns:
        p_col = 'pval'
    elif 'p' in welch.columns:
        p_col = 'p'
    else:
        print(welch.columns)
        raise KeyError("Could not find p-value column.")

    p_value = welch.loc[0, p_col]

    if p_value < 0.05:
        print('\n' + '='*60)
        print(f'Games-Howell post-hoc for {outcome}')

        gh = pg.pairwise_gameshowell(
            data=temp,
            dv=outcome,
            between=predictor
        )

        display(gh)

for outcome in score_outcomes:
    temp = df[[outcome, predictor]].dropna()

    summary = temp.groupby(predictor)[outcome].agg(['mean', 'count', 'std'])
    summary['se'] = summary['std'] / np.sqrt(summary['count'])
    summary['ci95'] = summary['se'] * stats.t.ppf(0.975, summary['count'] - 1)

    plt.figure(figsize=(8, 5))
    plt.errorbar(
        x=summary.index,
        y=summary['mean'],
        yerr=summary['ci95'],
        fmt='o',
        capsize=5
    )
    plt.title(f'Mean {outcome} by Financial Struggle Group with 95% CI')
    plt.xlabel('Financial Struggle Group')
    plt.ylabel(f'Mean {outcome}')
    plt.show()

score_outcomes = ['gad_total', 'phq_total', 'ptsd_total']
predictor = 'bill_difficulty_group'

bill_difficulty_results = []

for outcome in score_outcomes:
    temp = df[[outcome, predictor]].dropna()

    # Welch ANOVA
    welch = pg.welch_anova(
        data=temp,
        dv=outcome,
        between=predictor
    )

    # Detect p-value column safely
    if 'p_unc' in welch.columns:
        p_col = 'p_unc'
    elif 'pval' in welch.columns:
        p_col = 'pval'
    elif 'p' in welch.columns:
        p_col = 'p'
    else:
        print(welch.columns)
        raise KeyError("Could not find p-value column.")

    # Kruskal-Wallis robustness check
    groups = [
        group[outcome].values
        for name, group in temp.groupby(predictor)
    ]

    h_stat, kruskal_p = stats.kruskal(*groups)

    # Group summary
    group_summary = temp.groupby(predictor)[outcome].agg(
        ['count', 'mean', 'std']
    ).reset_index()

    bill_difficulty_results.append({
        'predictor': predictor,
        'outcome': outcome,
        'n': len(temp),
        'groups': temp[predictor].nunique(),
        'welch_F': round(welch.loc[0, 'F'], 3),
        'welch_p': round(welch.loc[0, p_col], 4),
        'welch_np2': round(welch.loc[0, 'np2'], 3) if 'np2' in welch.columns else np.nan,
        'kruskal_H': round(h_stat, 3),
        'kruskal_p': round(kruskal_p, 4),
        'group_summary': group_summary[[predictor, 'count', 'mean']].to_dict('records')
    })

bill_difficulty_welch_table = pd.DataFrame(bill_difficulty_results)
bill_difficulty_welch_table

for outcome in score_outcomes:
    temp = df[[outcome, predictor]].dropna()

    welch = pg.welch_anova(
        data=temp,
        dv=outcome,
        between=predictor
    )

    if 'p_unc' in welch.columns:
        p_col = 'p_unc'
    elif 'pval' in welch.columns:
        p_col = 'pval'
    elif 'p' in welch.columns:
        p_col = 'p'
    else:
        print(welch.columns)
        raise KeyError("Could not find p-value column.")

    p_value = welch.loc[0, p_col]

    if p_value < 0.05:
        print('\n' + '='*60)
        print(f'Games-Howell post-hoc for {outcome}')

        gh = pg.pairwise_gameshowell(
            data=temp,
            dv=outcome,
            between=predictor
        )

        print(gh.to_string()) # Changed display(gh) to print(gh.to_string()) for full output

for outcome in score_outcomes:
    temp = df[[outcome, predictor]].dropna()

    summary = temp.groupby(predictor)[outcome].agg(['mean', 'count', 'std'])
    summary['se'] = summary['std'] / np.sqrt(summary['count'])
    summary['ci95'] = summary['se'] * stats.t.ppf(0.975, summary['count'] - 1)

    plt.figure(figsize=(8, 5))
    plt.errorbar(
        x=summary.index,
        y=summary['mean'],
        yerr=summary['ci95'],
        fmt='o',
        capsize=5
    )
    plt.title(f'Mean {outcome} by Bill Difficulty Group with 95% CI')
    plt.xlabel('Bill Difficulty Group')
    plt.ylabel(f'Mean {outcome}')
    plt.show()

score_outcomes = ['gad_total', 'phq_total', 'ptsd_total']
predictor = 'income_stability_group'

income_stability_welch_results = []

for outcome in score_outcomes:
    temp = df[[outcome, predictor]].dropna()

    # Welch ANOVA
    welch = pg.welch_anova(
        data=temp,
        dv=outcome,
        between=predictor
    )

    # Kruskal-Wallis robustness check
    groups = [
        group[outcome].values
        for name, group in temp.groupby(predictor)
    ]

    h_stat, kruskal_p = stats.kruskal(*groups)

    # Group summary
    group_summary = temp.groupby(predictor)[outcome].agg(
        ['count', 'mean', 'std']
    ).reset_index()

    income_stability_welch_results.append({
        'predictor': predictor,
        'outcome': outcome,
        'n': len(temp),
        'groups': temp[predictor].nunique(),
        'welch_F': round(welch.loc[0, 'F'], 3),
        'welch_p': round(welch.loc[0, 'p_unc'], 4),
        'welch_np2': round(welch.loc[0, 'np2'], 3),
        'kruskal_H': round(h_stat, 3),
        'kruskal_p': round(kruskal_p, 4),
        'group_summary': group_summary[[predictor, 'count', 'mean']].to_dict('records')
    })

income_stability_welch_table = pd.DataFrame(income_stability_welch_results)
display(income_stability_welch_table)

for outcome in score_outcomes:
    temp = df[[outcome, predictor]].dropna()

    welch = pg.welch_anova(
        data=temp,
        dv=outcome,
        between=predictor
    )

    p_value = welch.loc[0, 'p_unc']

    if p_value < 0.05:
        print('\n' + '='*60)
        print(f'Games-Howell post-hoc for {outcome}')

        gh = pg.pairwise_gameshowell(
            data=temp,
            dv=outcome,
            between=predictor
        )

        display(gh)

for outcome in score_outcomes:
    temp = df[[outcome, predictor]].dropna()

    summary = temp.groupby(predictor)[outcome].agg(['mean', 'count', 'std'])
    summary['se'] = summary['std'] / np.sqrt(summary['count'])
    summary['ci95'] = summary['se'] * stats.t.ppf(0.975, summary['count'] - 1)

    plt.figure(figsize=(8, 5))
    plt.errorbar(
        x=summary.index,
        y=summary['mean'],
        yerr=summary['ci95'],
        fmt='o',
        capsize=5
    )
    plt.title(f'Mean {outcome} by Income Stability Group with 95% CI')
    plt.xlabel('Income Stability Group')
    plt.ylabel(f'Mean {outcome}')
    plt.xticks(rotation=20)
    plt.show()

# Service_access GP Vs mental Health
score_outcomes = ['gad_total', 'phq_total', 'ptsd_total']
predictor = 'service_access_group'

service_access_welch_results = []

for outcome in score_outcomes:
    temp = df[[outcome, predictor]].dropna()

    # Welch ANOVA
    welch = pg.welch_anova(
        data=temp,
        dv=outcome,
        between=predictor
    )

    # Kruskal-Wallis robustness check
    groups = [
        group[outcome].values
        for name, group in temp.groupby(predictor)
    ]

    h_stat, kruskal_p = stats.kruskal(*groups)

    # Group summary
    group_summary = temp.groupby(predictor)[outcome].agg(
        ['count', 'mean', 'std']
    ).reset_index()

    service_access_welch_results.append({
        'predictor': predictor,
        'outcome': outcome,
        'n': len(temp),
        'groups': temp[predictor].nunique(),
        'welch_F': round(welch.loc[0, 'F'], 3),
        'welch_p': round(welch.loc[0, 'p_unc'], 4),
        'welch_np2': round(welch.loc[0, 'np2'], 3),
        'kruskal_H': round(h_stat, 3),
        'kruskal_p': round(kruskal_p, 4),
        'group_summary': group_summary[[predictor, 'count', 'mean']].to_dict('records')
    })

service_access_welch_table = pd.DataFrame(service_access_welch_results)
display(service_access_welch_table)

for outcome in score_outcomes:
    temp = df[[outcome, predictor]].dropna()

    welch = pg.welch_anova(
        data=temp,
        dv=outcome,
        between=predictor
    )

    p_value = welch.loc[0, 'p_unc']

    if p_value < 0.05:
        print('\n' + '='*60)
        print(f'Games-Howell post-hoc for {outcome}')

        gh = pg.pairwise_gameshowell(
            data=temp,
            dv=outcome,
            between=predictor
        )

        display(gh)

for outcome in score_outcomes:
    temp = df[[outcome, predictor]].dropna()

    summary = temp.groupby(predictor)[outcome].agg(['mean', 'count', 'std'])
    summary['se'] = summary['std'] / np.sqrt(summary['count'])
    summary['ci95'] = summary['se'] * stats.t.ppf(0.975, summary['count'] - 1)

    plt.figure(figsize=(8, 5))
    plt.errorbar(
        x=summary.index,
        y=summary['mean'],
        yerr=summary['ci95'],
        fmt='o',
        capsize=5
    )
    plt.title(f'Mean {outcome} by Service Access Group with 95% CI')
    plt.xlabel('Service Access Group')
    plt.ylabel(f'Mean {outcome}')
    plt.xticks(rotation=20)
    plt.show()

anova_summary_results = []

# Employment Group (uses F-oneway and eta-squared)
for index, row in employment_anova_table.iterrows():
    anova_summary_results.append({
        'Predictor': row['predictor'],
        'Outcome': row['outcome'],
        'N': row['n'],
        'Groups': row['groups'],
        'F_statistic': row['anova_f'],
        'p_value': row['anova_p'],
        'Effect_Size_np2': row['eta_squared'],
        'Kruskal_H': row['kruskal_h'],
        'Kruskal_p': row['kruskal_p']
    })

# Other groups (use Welch ANOVA and welch_np2)
welch_tables = [
    income_welch_table,
    financial_stress_welch_table,
    financial_struggle_welch_table,
    bill_difficulty_welch_table,
    income_stability_welch_table,
    service_access_welch_table
]

for table in welch_tables:
    for index, row in table.iterrows():
        anova_summary_results.append({
            'Predictor': row['predictor'],
            'Outcome': row['outcome'],
            'N': row['n'],
            'Groups': row['groups'],
            'F_statistic': row['welch_F'],
            'p_value': row['welch_p'],
            'Effect_Size_np2': row['welch_np2'],
            'Kruskal_H': row['kruskal_H'],
            'Kruskal_p': row['kruskal_p']
        })

comparative_anova_summary = pd.DataFrame(anova_summary_results)
display(comparative_anova_summary.round(4))

"""### Key Findings from ANOVA Tests:

*   **Employment Group:** Significant differences for `gad_total` (unemployed higher). No significance for `phq_total` or `ptsd_total`.
*   **Income Group:** Significant differences for all three mental health outcomes (`gad_total`, `phq_total`, `ptsd_total`). Lower income generally reported higher distress.
*   **Financial Stress Group:** Significant differences for all three mental health outcomes. Higher stress associated with higher distress.
*   **Financial Struggle Group:** Significant differences for all three mental health outcomes. Higher struggle associated with higher distress.
*   **Bill Difficulty Group:** Significant differences for all three mental health outcomes. Higher difficulty associated with higher distress.
*   **Income Stability Group:** Significant differences for all three mental health outcomes. No/unstable income associated with higher distress.
*   **Service Access Group:** Significant differences for all three mental health outcomes. Hard access associated with higher distress.

# Tests: Chi_Square
"""

from scipy.stats import chi2_contingency
import pandas as pd
import numpy as np

# Define a function to perform a single Chi-Square test
def perform_chi_square_test(df, var1, var2):
    temp_df = df[[var1, var2]].dropna()

    # Special handling for 'conflict_impact_group' to exclude 'Other' category
    if var1 == 'conflict_impact_group':
        temp_df = temp_df[temp_df[var1] != 'Other']
    if var2 == 'conflict_impact_group':
        temp_df = temp_df[temp_df[var2] != 'Other']

    table = pd.crosstab(temp_df[var1], temp_df[var2])

    # Check if table is too sparse (e.g., after removing NAs, some categories might disappear)
    if table.empty or min(table.shape) < 2:
        return {
            'var1': var1,
            'var2': var2,
            'n': len(temp_df),
            'chi2': np.nan,
            'dof': np.nan,
            'p_value': np.nan,
            'cramers_v': np.nan,
            'low_expected_cells': np.nan,
            'total_cells': np.nan,
            'expected_count_warning': 'Insufficient data or categories'
        }

    chi2, p, dof, expected = chi2_contingency(table)

    n = table.values.sum()
    min_dim = min(table.shape) - 1

    cramers_v = np.sqrt(chi2 / (n * min_dim)) if min_dim > 0 else np.nan

    expected_df = pd.DataFrame(
        expected,
        index=table.index,
        columns=table.columns
    )

    low_expected_cells = (expected_df < 5).sum().sum()
    total_cells = expected_df.size

    return {
        'var1': var1,
        'var2': var2,
        'n': n,
        'chi2': round(chi2, 3),
        'dof': dof,
        'p_value': round(p, 4),
        'cramers_v': round(cramers_v, 3),
        'low_expected_cells': low_expected_cells,
        'total_cells': total_cells,
        'expected_count_warning': 'Yes' if low_expected_cells > 0 else 'No'
    }

# Extended list of Chi-Square tests to perform
chi_tests = [
    ('education_group', 'income_group'),
    ('employment_group', 'income_group'),
    ('income_group', 'housing_group'),
    ('income_group', 'healthcare_access_group'),
    ('living_area', 'service_access_group'),
    ('conflict_impact_group', 'housing_group'),
    ('conflict_impact_group', 'healthcare_access_group'),
    # New tests:
    ('gender_group', 'education_group'),
    ('gender_group', 'employment_group'),
    ('marital_status', 'income_group'), # Using original 'marital_status'
    ('resident_status', 'housing_group'), # Using original 'resident_status'
    ('financial_struggle_group', 'financial_stress_group'),
    ('bill_difficulty_group', 'service_access_group'),
    ('education_group', 'healthcare_access_group')
]

chi_results = []

for var1, var2 in chi_tests:
    result = perform_chi_square_test(df, var1, var2)
    chi_results.append(result)

chi_square_summary = pd.DataFrame(chi_results)
chi_square_summary

for var1, var2 in chi_tests:
    temp = df[[var1, var2]].dropna()

    # Optional: remove "Other" from conflict impact if present (handled in function, but keeping for consistency if not using function)
    if var1 == 'conflict_impact_group':
        temp = temp[temp[var1] != 'Other']
    if var2 == 'conflict_impact_group':
        temp = temp[temp[var2] != 'Other']

    print('\n' + '='*70)
    print(f'{var1} x {var2}')

    count_table = pd.crosstab(temp[var1], temp[var2])
    percent_table = pd.crosstab(
        temp[var1],
        temp[var2],
        normalize='index'
    ) * 100

    print('\nCounts:')
    display(count_table)

    print('\nRow percentages:')
    display(percent_table.round(1))



new_chi_tests_to_display = [
    ('gender_group', 'education_group'),
    ('gender_group', 'employment_group'),
    ('marital_status', 'income_group'),
    ('resident_status', 'housing_group'),
    ('financial_struggle_group', 'financial_stress_group'),
    ('bill_difficulty_group', 'service_access_group'),
    ('education_group', 'healthcare_access_group')
]

for var1, var2 in new_chi_tests_to_display:
    temp = df[[var1, var2]].dropna()

    # Special handling for 'conflict_impact_group' is not strictly needed here
    # as these are new pairs not involving conflict_impact_group in var1, but kept
    # for consistency if the list were to be modified.
    if var1 == 'conflict_impact_group':
        temp = temp[temp[var1] != 'Other']
    if var2 == 'conflict_impact_group':
        temp = temp[temp[var2] != 'Other']

    print('\n' + '='*70)
    print(f'{var1} x {var2}')

    count_table = pd.crosstab(temp[var1], temp[var2])
    percent_table = pd.crosstab(
        temp[var1],
        temp[var2],
        normalize='index'
    ) * 100

    print('\nCounts:')
    display(count_table)

    print('\nRow percentages:')
    display(percent_table.round(1))

# Note: The chi_square_summary DataFrame already contains results for these new tests.

import matplotlib.pyplot as plt

# Selected chi-square associations for final report
chi_report_tests = [
    ('income_group', 'housing_group', 'Income Group and Housing Stability'),
    ('income_group', 'healthcare_access_group', 'Income Group and Healthcare Access'),
    ('living_area', 'service_access_group', 'Living Area and Access to Services'),
    ('conflict_impact_group', 'housing_group', 'Conflict Impact and Housing Stability')
]

# Clean display labels without changing original dataframe
label_replacements = {
    'Stable housing': 'Stable',
    'Unstable housing': 'Unstable',
    'Has access': 'Has access',
    'Limited/no access': 'Limited / no access',
    'Rural (villages, countryside)': 'Rural',
    'Urban ( City, Town)': 'Urban',
    'No/Mild Impact': 'No / Mild impact',
    'Moderate/Severe Impact': 'Moderate / Severe impact'
}

for var1, var2, plot_title in chi_report_tests:
    temp = df[[var1, var2]].dropna().copy()

    # Remove "Other" category from conflict impact if present
    if var1 == 'conflict_impact_group':
        temp = temp[temp[var1] != 'Other']
    if var2 == 'conflict_impact_group':
        temp = temp[temp[var2] != 'Other']

    # Apply clean labels only for plotting
    temp[var1] = temp[var1].replace(label_replacements)
    temp[var2] = temp[var2].replace(label_replacements)

    # Create row percentage table
    percent_table = pd.crosstab(
        temp[var1],
        temp[var2],
        normalize='index'
    ) * 100

    # Plot 100% stacked bar chart
    ax = percent_table.plot(
        kind='bar',
        stacked=True,
        figsize=(8, 5)
    )

    plt.title(plot_title)
    plt.xlabel('')
    plt.ylabel('Percentage of respondents')
    plt.xticks(rotation=15)
    plt.legend(
        title=var2.replace('_', ' ').title(),
        bbox_to_anchor=(1.05, 1),
        loc='upper left'
    )

    # Add percentage labels inside bars
    for container in ax.containers:
        labels = [
            f'{value:.1f}%' if value >= 5 else ''
            for value in container.datavalues
        ]
        ax.bar_label(
            container,
            labels=labels,
            label_type='center',
            fontsize=9
        )

    plt.tight_layout()
    plt.show()

"""##Key Findings from Chi_Square Tests

 * Income Group and Housing Stability (Cramér's V = 0.284): This plot illustrates a moderate association between income group and housing stability. Individuals in lower income groups tend to report higher percentages of unstable housing situations, while those in higher income groups show a greater proportion of stable housing. For example, a larger percentage of 'Low income' respondents reported 'Unstable' housing compared to 'High income' respondents.

* Income Group and Healthcare Access (Cramér's V = 0.304): This plot shows a moderate association, indicating that healthcare access varies across income groups. A higher proportion of individuals in 'Limited / no access' healthcare groups are found within the 'Low income' category, whereas 'Has access' is more prevalent in 'High income' groups.

* Living Area and Access to Services (Cramér's V = 0.437): This plot reveals a strong association. Respondents from 'Rural' areas disproportionately report 'Hard' access to services, while those in 'Urban' areas generally experience 'Easy' or 'Moderate' access. The differences in access levels are quite pronounced between rural and urban living areas.

* Conflict Impact and Housing Stability (Cramér's V = 0.283): This plot indicates a moderate association. Individuals who experienced 'Moderate / Severe impact' from conflict show a higher percentage of 'Unstable' housing compared to those with 'No / Mild impact', who predominantly report 'Stable' housing. This suggests that the severity of conflict impact is linked to housing stability.
"""

